/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { AddVirtualFolderDtoLibraryOptions } from "./addVirtualFolderDtoLibraryOptions";

/**
 * Add virtual folder dto.
 */
export interface AddVirtualFolderDto {
  /**
   * Gets or sets library options.
   * @nullable
   */
  LibraryOptions?: AddVirtualFolderDtoLibraryOptions;
}
