/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ThemeMediaResult } from "./themeMediaResult";

/**
 * Class ThemeMediaResult.
 * @nullable
 */
export type AllThemeMediaResultSoundtrackSongsResult = ThemeMediaResult | null;
