/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { BaseItemPersonImageBlurHashesArt } from "./baseItemPersonImageBlurHashesArt";
import type { BaseItemPersonImageBlurHashesBackdrop } from "./baseItemPersonImageBlurHashesBackdrop";
import type { BaseItemPersonImageBlurHashesBanner } from "./baseItemPersonImageBlurHashesBanner";
import type { BaseItemPersonImageBlurHashesBox } from "./baseItemPersonImageBlurHashesBox";
import type { BaseItemPersonImageBlurHashesBoxRear } from "./baseItemPersonImageBlurHashesBoxRear";
import type { BaseItemPersonImageBlurHashesChapter } from "./baseItemPersonImageBlurHashesChapter";
import type { BaseItemPersonImageBlurHashesDisc } from "./baseItemPersonImageBlurHashesDisc";
import type { BaseItemPersonImageBlurHashesLogo } from "./baseItemPersonImageBlurHashesLogo";
import type { BaseItemPersonImageBlurHashesMenu } from "./baseItemPersonImageBlurHashesMenu";
import type { BaseItemPersonImageBlurHashesPrimary } from "./baseItemPersonImageBlurHashesPrimary";
import type { BaseItemPersonImageBlurHashesProfile } from "./baseItemPersonImageBlurHashesProfile";
import type { BaseItemPersonImageBlurHashesScreenshot } from "./baseItemPersonImageBlurHashesScreenshot";
import type { BaseItemPersonImageBlurHashesThumb } from "./baseItemPersonImageBlurHashesThumb";

/**
 * Gets or sets the primary image blurhash.
 * @nullable
 */
export type BaseItemPersonImageBlurHashes = {
  Art?: BaseItemPersonImageBlurHashesArt;
  Backdrop?: BaseItemPersonImageBlurHashesBackdrop;
  Banner?: BaseItemPersonImageBlurHashesBanner;
  Box?: BaseItemPersonImageBlurHashesBox;
  BoxRear?: BaseItemPersonImageBlurHashesBoxRear;
  Chapter?: BaseItemPersonImageBlurHashesChapter;
  Disc?: BaseItemPersonImageBlurHashesDisc;
  Logo?: BaseItemPersonImageBlurHashesLogo;
  Menu?: BaseItemPersonImageBlurHashesMenu;
  Primary?: BaseItemPersonImageBlurHashesPrimary;
  Profile?: BaseItemPersonImageBlurHashesProfile;
  Screenshot?: BaseItemPersonImageBlurHashesScreenshot;
  Thumb?: BaseItemPersonImageBlurHashesThumb;
} | null;
