/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlayAccess } from "./playAccess";

/**
 * Gets or sets the play access.
 * @nullable
 */
export type BaseItemDtoPlayAccess = PlayAccess | null;
