/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { UserItemDataDto } from "./userItemDataDto";

/**
 * Gets or sets the user data for this item based on the user it's being requested for.
 * @nullable
 */
export type BaseItemDtoUserData = UserItemDataDto | null;
