/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { VideoType } from "./videoType";

/**
 * Gets or sets the type of the video.
 * @nullable
 */
export type BaseItemDtoVideoType = VideoType | null;
