/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ChannelType } from './channelType';

/**
 * Gets or sets the type of the channel.
 */
export type BaseItemDtoChannelType = ChannelType | null;
