/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { LocationType } from './locationType';

/**
 * Gets or sets the type of the location.
 */
export type BaseItemDtoLocationType = LocationType | null;
