/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { IsoType } from "./isoType";

/**
 * Gets or sets the type of the iso.
 * @nullable
 */
export type BaseItemDtoIsoType = IsoType | null;
