/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { BaseItemDtoVideo3DFormat } from "./baseItemDtoVideo3DFormat";
import type { ExternalUrl } from "./externalUrl";
import type { MediaSourceInfo } from "./mediaSourceInfo";
import type { BaseItemDtoPlayAccess } from "./baseItemDtoPlayAccess";
import type { MediaUrl } from "./mediaUrl";
import type { BaseItemDtoProviderIds } from "./baseItemDtoProviderIds";
import type { BaseItemKind } from "./baseItemKind";
import type { BaseItemPerson } from "./baseItemPerson";
import type { NameGuidPair } from "./nameGuidPair";
import type { BaseItemDtoUserData } from "./baseItemDtoUserData";
import type { DayOfWeek } from "./dayOfWeek";
import type { MediaStream } from "./mediaStream";
import type { BaseItemDtoVideoType } from "./baseItemDtoVideoType";
import type { BaseItemDtoImageTags } from "./baseItemDtoImageTags";
import type { BaseItemDtoImageBlurHashes } from "./baseItemDtoImageBlurHashes";
import type { ChapterInfo } from "./chapterInfo";
import type { BaseItemDtoLocationType } from "./baseItemDtoLocationType";
import type { BaseItemDtoIsoType } from "./baseItemDtoIsoType";
import type { MetadataField } from "./metadataField";
import type { BaseItemDtoImageOrientation } from "./baseItemDtoImageOrientation";
import type { BaseItemDtoChannelType } from "./baseItemDtoChannelType";
import type { BaseItemDtoAudio } from "./baseItemDtoAudio";
import type { BaseItemDtoCurrentProgram } from "./baseItemDtoCurrentProgram";

/**
 * This is strictly used as a data transfer object from the api layer.
This holds information about a BaseItem in a format that is convenient for the client.
 */
export interface BaseItemDto {
  /** Gets or sets the name. */
  Name?: string | null;
  OriginalTitle?: string | null;
  /** Gets or sets the server identifier. */
  ServerId?: string | null;
  /** Gets or sets the id. */
  Id?: string;
  /** Gets or sets the etag. */
  Etag?: string | null;
  /** Gets or sets the type of the source. */
  SourceType?: string | null;
  /** Gets or sets the playlist item identifier. */
  PlaylistItemId?: string | null;
  /** Gets or sets the date created. */
  DateCreated?: string | null;
  DateLastMediaAdded?: string | null;
  ExtraType?: string | null;
  AirsBeforeSeasonNumber?: number | null;
  AirsAfterSeasonNumber?: number | null;
  AirsBeforeEpisodeNumber?: number | null;
  CanDelete?: boolean | null;
  CanDownload?: boolean | null;
  HasSubtitles?: boolean | null;
  PreferredMetadataLanguage?: string | null;
  PreferredMetadataCountryCode?: string | null;
  /** Gets or sets a value indicating whether [supports synchronize]. */
  SupportsSync?: boolean | null;
  Container?: string | null;
  /** Gets or sets the name of the sort. */
  SortName?: string | null;
  ForcedSortName?: string | null;
  /** Gets or sets the video3 D format. */
  Video3DFormat?: BaseItemDtoVideo3DFormat;
  /** Gets or sets the premiere date. */
  PremiereDate?: string | null;
  /** Gets or sets the external urls. */
  ExternalUrls?: ExternalUrl[] | null;
  /** Gets or sets the media versions. */
  MediaSources?: MediaSourceInfo[] | null;
  /** Gets or sets the critic rating. */
  CriticRating?: number | null;
  ProductionLocations?: string[] | null;
  /** Gets or sets the path. */
  Path?: string | null;
  EnableMediaSourceDisplay?: boolean | null;
  /** Gets or sets the official rating. */
  OfficialRating?: string | null;
  /** Gets or sets the custom rating. */
  CustomRating?: string | null;
  /** Gets or sets the channel identifier. */
  ChannelId?: string | null;
  ChannelName?: string | null;
  /** Gets or sets the overview. */
  Overview?: string | null;
  /** Gets or sets the taglines. */
  Taglines?: string[] | null;
  /** Gets or sets the genres. */
  Genres?: string[] | null;
  /** Gets or sets the community rating. */
  CommunityRating?: number | null;
  /** Gets or sets the cumulative run time ticks. */
  CumulativeRunTimeTicks?: number | null;
  /** Gets or sets the run time ticks. */
  RunTimeTicks?: number | null;
  /** Gets or sets the play access. */
  PlayAccess?: BaseItemDtoPlayAccess;
  /** Gets or sets the aspect ratio. */
  AspectRatio?: string | null;
  /** Gets or sets the production year. */
  ProductionYear?: number | null;
  /** Gets or sets a value indicating whether this instance is place holder. */
  IsPlaceHolder?: boolean | null;
  /** Gets or sets the number. */
  Number?: string | null;
  ChannelNumber?: string | null;
  /** Gets or sets the index number. */
  IndexNumber?: number | null;
  /** Gets or sets the index number end. */
  IndexNumberEnd?: number | null;
  /** Gets or sets the parent index number. */
  ParentIndexNumber?: number | null;
  /** Gets or sets the trailer urls. */
  RemoteTrailers?: MediaUrl[] | null;
  /** Gets or sets the provider ids. */
  ProviderIds?: BaseItemDtoProviderIds;
  /** Gets or sets a value indicating whether this instance is HD. */
  IsHD?: boolean | null;
  /** Gets or sets a value indicating whether this instance is folder. */
  IsFolder?: boolean | null;
  /** Gets or sets the parent id. */
  ParentId?: string | null;
  /** The base item kind. */
  Type?: BaseItemKind;
  /** Gets or sets the people. */
  People?: BaseItemPerson[] | null;
  /** Gets or sets the studios. */
  Studios?: NameGuidPair[] | null;
  GenreItems?: NameGuidPair[] | null;
  /** Gets or sets wether the item has a logo, this will hold the Id of the Parent that has one. */
  ParentLogoItemId?: string | null;
  /** Gets or sets wether the item has any backdrops, this will hold the Id of the Parent that has one. */
  ParentBackdropItemId?: string | null;
  /** Gets or sets the parent backdrop image tags. */
  ParentBackdropImageTags?: string[] | null;
  /** Gets or sets the local trailer count. */
  LocalTrailerCount?: number | null;
  /** Gets or sets the user data for this item based on the user it's being requested for. */
  UserData?: BaseItemDtoUserData;
  /** Gets or sets the recursive item count. */
  RecursiveItemCount?: number | null;
  /** Gets or sets the child count. */
  ChildCount?: number | null;
  /** Gets or sets the name of the series. */
  SeriesName?: string | null;
  /** Gets or sets the series id. */
  SeriesId?: string | null;
  /** Gets or sets the season identifier. */
  SeasonId?: string | null;
  /** Gets or sets the special feature count. */
  SpecialFeatureCount?: number | null;
  /** Gets or sets the display preferences id. */
  DisplayPreferencesId?: string | null;
  /** Gets or sets the status. */
  Status?: string | null;
  /** Gets or sets the air time. */
  AirTime?: string | null;
  /** Gets or sets the air days. */
  AirDays?: DayOfWeek[] | null;
  /** Gets or sets the tags. */
  Tags?: string[] | null;
  /** Gets or sets the primary image aspect ratio, after image enhancements. */
  PrimaryImageAspectRatio?: number | null;
  /** Gets or sets the artists. */
  Artists?: string[] | null;
  /** Gets or sets the artist items. */
  ArtistItems?: NameGuidPair[] | null;
  /** Gets or sets the album. */
  Album?: string | null;
  /** Gets or sets the type of the collection. */
  CollectionType?: string | null;
  /** Gets or sets the display order. */
  DisplayOrder?: string | null;
  /** Gets or sets the album id. */
  AlbumId?: string | null;
  /** Gets or sets the album image tag. */
  AlbumPrimaryImageTag?: string | null;
  /** Gets or sets the series primary image tag. */
  SeriesPrimaryImageTag?: string | null;
  /** Gets or sets the album artist. */
  AlbumArtist?: string | null;
  /** Gets or sets the album artists. */
  AlbumArtists?: NameGuidPair[] | null;
  /** Gets or sets the name of the season. */
  SeasonName?: string | null;
  /** Gets or sets the media streams. */
  MediaStreams?: MediaStream[] | null;
  /** Gets or sets the type of the video. */
  VideoType?: BaseItemDtoVideoType;
  /** Gets or sets the part count. */
  PartCount?: number | null;
  MediaSourceCount?: number | null;
  /** Gets or sets the image tags. */
  ImageTags?: BaseItemDtoImageTags;
  /** Gets or sets the backdrop image tags. */
  BackdropImageTags?: string[] | null;
  /** Gets or sets the screenshot image tags. */
  ScreenshotImageTags?: string[] | null;
  /** Gets or sets the parent logo image tag. */
  ParentLogoImageTag?: string | null;
  /** Gets or sets wether the item has fan art, this will hold the Id of the Parent that has one. */
  ParentArtItemId?: string | null;
  /** Gets or sets the parent art image tag. */
  ParentArtImageTag?: string | null;
  /** Gets or sets the series thumb image tag. */
  SeriesThumbImageTag?: string | null;
  /** Gets or sets the blurhashes for the image tags.
Maps image type to dictionary mapping image tag to blurhash value. */
  ImageBlurHashes?: BaseItemDtoImageBlurHashes;
  /** Gets or sets the series studio. */
  SeriesStudio?: string | null;
  /** Gets or sets the parent thumb item id. */
  ParentThumbItemId?: string | null;
  /** Gets or sets the parent thumb image tag. */
  ParentThumbImageTag?: string | null;
  /** Gets or sets the parent primary image item identifier. */
  ParentPrimaryImageItemId?: string | null;
  /** Gets or sets the parent primary image tag. */
  ParentPrimaryImageTag?: string | null;
  /** Gets or sets the chapters. */
  Chapters?: ChapterInfo[] | null;
  /** Gets or sets the type of the location. */
  LocationType?: BaseItemDtoLocationType;
  /** Gets or sets the type of the iso. */
  IsoType?: BaseItemDtoIsoType;
  /** Gets or sets the type of the media. */
  MediaType?: string | null;
  /** Gets or sets the end date. */
  EndDate?: string | null;
  /** Gets or sets the locked fields. */
  LockedFields?: MetadataField[] | null;
  /** Gets or sets the trailer count. */
  TrailerCount?: number | null;
  /** Gets or sets the movie count. */
  MovieCount?: number | null;
  /** Gets or sets the series count. */
  SeriesCount?: number | null;
  ProgramCount?: number | null;
  /** Gets or sets the episode count. */
  EpisodeCount?: number | null;
  /** Gets or sets the song count. */
  SongCount?: number | null;
  /** Gets or sets the album count. */
  AlbumCount?: number | null;
  ArtistCount?: number | null;
  /** Gets or sets the music video count. */
  MusicVideoCount?: number | null;
  /** Gets or sets a value indicating whether [enable internet providers]. */
  LockData?: boolean | null;
  Width?: number | null;
  Height?: number | null;
  CameraMake?: string | null;
  CameraModel?: string | null;
  Software?: string | null;
  ExposureTime?: number | null;
  FocalLength?: number | null;
  ImageOrientation?: BaseItemDtoImageOrientation;
  Aperture?: number | null;
  ShutterSpeed?: number | null;
  Latitude?: number | null;
  Longitude?: number | null;
  Altitude?: number | null;
  IsoSpeedRating?: number | null;
  /** Gets or sets the series timer identifier. */
  SeriesTimerId?: string | null;
  /** Gets or sets the program identifier. */
  ProgramId?: string | null;
  /** Gets or sets the channel primary image tag. */
  ChannelPrimaryImageTag?: string | null;
  /** Gets or sets the start date of the recording, in UTC. */
  StartDate?: string | null;
  /** Gets or sets the completion percentage. */
  CompletionPercentage?: number | null;
  /** Gets or sets a value indicating whether this instance is repeat. */
  IsRepeat?: boolean | null;
  /** Gets or sets the episode title. */
  EpisodeTitle?: string | null;
  /** Gets or sets the type of the channel. */
  ChannelType?: BaseItemDtoChannelType;
  /** Gets or sets the audio. */
  Audio?: BaseItemDtoAudio;
  /** Gets or sets a value indicating whether this instance is movie. */
  IsMovie?: boolean | null;
  /** Gets or sets a value indicating whether this instance is sports. */
  IsSports?: boolean | null;
  /** Gets or sets a value indicating whether this instance is series. */
  IsSeries?: boolean | null;
  /** Gets or sets a value indicating whether this instance is live. */
  IsLive?: boolean | null;
  /** Gets or sets a value indicating whether this instance is news. */
  IsNews?: boolean | null;
  /** Gets or sets a value indicating whether this instance is kids. */
  IsKids?: boolean | null;
  /** Gets or sets a value indicating whether this instance is premiere. */
  IsPremiere?: boolean | null;
  /** Gets or sets the timer identifier. */
  TimerId?: string | null;
  /** Gets or sets the current program. */
  CurrentProgram?: BaseItemDtoCurrentProgram;
}
