/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { BookInfo } from "./bookInfo";

/**
 * @nullable
 */
export type BookInfoRemoteSearchQuerySearchInfo = BookInfo | null;
