/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * The branding options.
 */
export interface BrandingOptions {
  /**
   * Gets or sets the custom CSS.
   * @nullable
   */
  CustomCss?: string | null;
  /**
   * Gets or sets the login disclaimer.
   * @nullable
   */
  LoginDisclaimer?: string | null;
  /** Gets or sets a value indicating whether to enable the splashscreen. */
  SplashscreenEnabled?: boolean;
}
