/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Enum ChannelType.
 */
export type ChannelType = (typeof ChannelType)[keyof typeof ChannelType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelType = {
  TV: "TV",
  Radio: "Radio",
} as const;
