/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { TunerChannelMapping } from "./tunerChannelMapping";
import type { NameIdPair } from "./nameIdPair";
import type { NameValuePair } from "./nameValuePair";

/**
 * Channel mapping options dto.
 */
export interface ChannelMappingOptionsDto {
  /** Gets or sets list of tuner channels. */
  TunerChannels?: TunerChannelMapping[];
  /** Gets or sets list of provider channels. */
  ProviderChannels?: NameIdPair[];
  /** Gets or sets list of mappings. */
  Mappings?: NameValuePair[];
  /** Gets or sets provider name. */
  ProviderName?: string | null;
}
