/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type ChannelItemSortField =
  (typeof ChannelItemSortField)[keyof typeof ChannelItemSortField];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelItemSortField = {
  Name: "Name",
  CommunityRating: "CommunityRating",
  PremiereDate: "PremiereDate",
  DateCreated: "DateCreated",
  Runtime: "Runtime",
  PlayCount: "PlayCount",
  CommunityPlayCount: "CommunityPlayCount",
} as const;
