/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ClientCapabilitiesDeviceProfile } from "./clientCapabilitiesDeviceProfile";
import type { GeneralCommandType } from "./generalCommandType";

export interface ClientCapabilities {
  /** @nullable */
  AppStoreUrl?: string | null;
  /**
   * A MediaBrowser.Model.Dlna.DeviceProfile represents a set of metadata which determines which content a certain device is able to play.
<br />
Specifically, it defines the supported <see cref="P:MediaBrowser.Model.Dlna.DeviceProfile.ContainerProfiles">containers</see> and
<see cref="P:MediaBrowser.Model.Dlna.DeviceProfile.CodecProfiles">codecs</see> (video and/or audio, including codec profiles and levels)
the device is able to direct play (without transcoding or remuxing),
as well as which <see cref="P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles">containers/codecs to transcode to</see> in case it isn't.
   * @nullable
   */
  DeviceProfile?: ClientCapabilitiesDeviceProfile;
  /** @nullable */
  IconUrl?: string | null;
  /** @nullable */
  MessageCallbackUrl?: string | null;
  /** @nullable */
  PlayableMediaTypes?: string[] | null;
  /** @nullable */
  SupportedCommands?: GeneralCommandType[] | null;
  SupportsContentUploading?: boolean;
  SupportsMediaControl?: boolean;
  SupportsPersistentIdentifier?: boolean;
  SupportsSync?: boolean;
}
