/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { GeneralCommandType } from "./generalCommandType";
import type { ClientCapabilitiesDtoDeviceProfile } from "./clientCapabilitiesDtoDeviceProfile";

/**
 * Client capabilities dto.
 */
export interface ClientCapabilitiesDto {
  /** Gets or sets the list of playable media types. */
  PlayableMediaTypes?: string[];
  /** Gets or sets the list of supported commands. */
  SupportedCommands?: GeneralCommandType[];
  /** Gets or sets a value indicating whether session supports media control. */
  SupportsMediaControl?: boolean;
  /** Gets or sets a value indicating whether session supports content uploading. */
  SupportsContentUploading?: boolean;
  /** Gets or sets the message callback url. */
  MessageCallbackUrl?: string | null;
  /** Gets or sets a value indicating whether session supports a persistent identifier. */
  SupportsPersistentIdentifier?: boolean;
  /** Gets or sets a value indicating whether session supports sync. */
  SupportsSync?: boolean;
  /** Gets or sets the device profile. */
  DeviceProfile?: ClientCapabilitiesDtoDeviceProfile;
  /** Gets or sets the app store url. */
  AppStoreUrl?: string | null;
  /** Gets or sets the icon url. */
  IconUrl?: string | null;
}
