/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type CodecType = (typeof CodecType)[keyof typeof CodecType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CodecType = {
  Video: "Video",
  VideoAudio: "VideoAudio",
  Audio: "Audio",
} as const;
