/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { CodecType } from './codecType';
import type { ProfileCondition } from './profileCondition';

export interface CodecProfile {
  Type?: CodecType;
  Conditions?: ProfileCondition[] | null;
  ApplyConditions?: ProfileCondition[] | null;
  Codec?: string | null;
  Container?: string | null;
}
