/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * The configuration page info.
 */
export interface ConfigurationPageInfo {
  /**
   * Gets or sets the display name.
   * @nullable
   */
  DisplayName?: string | null;
  /** Gets or sets a value indicating whether the configurations page is enabled in the main menu. */
  EnableInMainMenu?: boolean;
  /**
   * Gets or sets the menu icon.
   * @nullable
   */
  MenuIcon?: string | null;
  /**
   * Gets or sets the menu section.
   * @nullable
   */
  MenuSection?: string | null;
  /** Gets or sets the name. */
  Name?: string;
  /**
   * Gets or sets the plugin id.
   * @nullable
   */
  PluginId?: string | null;
}
