/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { DlnaProfileType } from "./dlnaProfileType";
import type { ProfileCondition } from "./profileCondition";

export interface ContainerProfile {
  Type?: DlnaProfileType;
  Conditions?: ProfileCondition[] | null;
  Container?: string;
}
