/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ProfileCondition } from "./profileCondition";
import type { DlnaProfileType } from "./dlnaProfileType";

export interface ContainerProfile {
  /** @nullable */
  Conditions?: ProfileCondition[] | null;
  Container?: string;
  Type?: DlnaProfileType;
}
