/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * The create user by name request body.
 */
export interface CreateUserByName {
  /**
   * Gets or sets the username.
   * @nullable
   */
  Name?: string | null;
  /**
   * Gets or sets the password.
   * @nullable
   */
  Password?: string | null;
}
