/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type CreatePlaylistParams = {
  /**
   * The playlist name.
   * @deprecated
   */
  name?: string;
  /**
   * The item ids.
   * @deprecated
   */
  ids?: string[];
  /**
   * The user id.
   * @deprecated
   */
  userId?: string;
  /**
   * The media type.
   * @deprecated
   */
  mediaType?: string;
};
