/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Default directory browser info.
 */
export interface DefaultDirectoryBrowserInfoDto {
  /**
   * Gets or sets the path.
   * @nullable
   */
  Path?: string | null;
}
