/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { DeviceIdentification } from "./deviceIdentification";

/**
 * Gets or sets the Identification.
 * @nullable
 */
export type DeviceProfileIdentification = DeviceIdentification | null;
