/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * An entity representing custom options for a device.
 */
export interface DeviceOptions {
  /** Gets the id. */
  readonly Id?: number;
  /** Gets the device id. */
  DeviceId?: string;
  /** Gets or sets the custom name. */
  CustomName?: string | null;
}
