/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { DlnaProfileType } from "./dlnaProfileType";

export interface DirectPlayProfile {
  /** @nullable */
  AudioCodec?: string | null;
  /** @nullable */
  Container?: string | null;
  Type?: DlnaProfileType;
  /** @nullable */
  VideoCodec?: string | null;
}
