/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { BaseItemKind } from "./baseItemKind";

export type DisplayContentParams = {
  itemType: BaseItemKind;
  itemId: string;
  itemName: string;
};
