/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { DisplayPreferencesDtoCustomPrefs } from "./displayPreferencesDtoCustomPrefs";
import type { ScrollDirection } from "./scrollDirection";
import type { SortOrder } from "./sortOrder";

/**
 * Defines the display preferences for any item that supports them (usually Folders).
 */
export interface DisplayPreferencesDto {
  /**
   * Gets or sets the client.
   * @nullable
   */
  Client?: string | null;
  /** Gets or sets the custom prefs. */
  CustomPrefs?: DisplayPreferencesDtoCustomPrefs;
  /**
   * Gets or sets the user id.
   * @nullable
   */
  Id?: string | null;
  /**
   * Gets or sets the index by.
   * @nullable
   */
  IndexBy?: string | null;
  /** Gets or sets the height of the primary image. */
  PrimaryImageHeight?: number;
  /** Gets or sets the width of the primary image. */
  PrimaryImageWidth?: number;
  /** Gets or sets a value indicating whether [remember indexing]. */
  RememberIndexing?: boolean;
  /** Gets or sets a value indicating whether [remember sorting]. */
  RememberSorting?: boolean;
  /** An enum representing the axis that should be scrolled. */
  ScrollDirection?: ScrollDirection;
  /** Gets or sets a value indicating whether to show backdrops on this item. */
  ShowBackdrop?: boolean;
  /** Gets or sets a value indicating whether [show sidebar]. */
  ShowSidebar?: boolean;
  /**
   * Gets or sets the sort by.
   * @nullable
   */
  SortBy?: string | null;
  /** An enum representing the sorting order. */
  SortOrder?: SortOrder;
  /**
   * Gets or sets the type of the view.
   * @nullable
   */
  ViewType?: string | null;
}
