/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ImageType } from "./imageType";

export type DownloadRemoteImageParams = {
  /**
   * The image type.
   */
  type: ImageType;
  /**
   * The image url.
   */
  imageUrl?: string;
};
