/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ImageType } from "./imageType";

export type DownloadRemoteImageParams = { type: ImageType; imageUrl?: string };
