/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * An enum representing the options to disable embedded subs.
 */
export type EmbeddedSubtitleOptions =
  (typeof EmbeddedSubtitleOptions)[keyof typeof EmbeddedSubtitleOptions];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmbeddedSubtitleOptions = {
  AllowAll: "AllowAll",
  AllowText: "AllowText",
  AllowImage: "AllowImage",
  AllowNone: "AllowNone",
} as const;
