/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Enum describing the location of the FFmpeg tool.
 */
export type FFmpegLocation = typeof FFmpegLocation[keyof typeof FFmpegLocation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FFmpegLocation = {
  NotFound: 'NotFound',
  SetByArgument: 'SetByArgument',
  Custom: 'Custom',
  System: 'System',
} as const;
