/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { FileSystemEntryType } from "./fileSystemEntryType";

/**
 * Class FileSystemEntryInfo.
 */
export interface FileSystemEntryInfo {
  /** Gets the name. */
  Name?: string;
  /** Gets the path. */
  Path?: string;
  /** Gets the type. */
  Type?: FileSystemEntryType;
}
