/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Enum FileSystemEntryType.
 */
export type FileSystemEntryType =
  (typeof FileSystemEntryType)[keyof typeof FileSystemEntryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileSystemEntryType = {
  File: "File",
  Directory: "Directory",
  NetworkComputer: "NetworkComputer",
  NetworkShare: "NetworkShare",
} as const;
