/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class FontFile.
 */
export interface FontFile {
  /** Gets or sets the date created. */
  DateCreated?: string;
  /** Gets or sets the date modified. */
  DateModified?: string;
  /**
   * Gets or sets the name.
   * @nullable
   */
  Name?: string | null;
  /** Gets or sets the size. */
  Size?: number;
}
