/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Forgot Password Pin enter request body DTO.
 */
export interface ForgotPasswordPinDto {
  /** Gets or sets the entered pin to have the password reset. */
  Pin: string;
}
