/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { SortOrder } from "./sortOrder";
import type { ItemFilter } from "./itemFilter";
import type { ItemFields } from "./itemFields";

export type GetChannelItemsParams = {
  folderId?: string;
  userId?: string;
  startIndex?: number;
  limit?: number;
  sortOrder?: SortOrder[];
  filters?: ItemFilter[];
  sortBy?: string[];
  fields?: ItemFields[];
};
