/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type GetChannelsParams = {
  /**
   * User Id to filter by. Use System.Guid.Empty to not filter by user.
   */
  userId?: string;
  /**
   * Optional. The record index to start at. All items with a lower index will be dropped from the results.
   */
  startIndex?: number;
  /**
   * Optional. The maximum number of records to return.
   */
  limit?: number;
  /**
   * Optional. Filter by channels that support getting latest items.
   */
  supportsLatestItems?: boolean;
  /**
   * Optional. Filter by channels that support media deletion.
   */
  supportsMediaDeletion?: boolean;
  /**
   * Optional. Filter by channels that are favorite.
   */
  isFavorite?: boolean;
};
