/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { SortOrder } from "./sortOrder";
import type { ItemFilter } from "./itemFilter";
import type { ItemFields } from "./itemFields";

export type GetChannelItemsParams = {
  /**
   * Optional. Folder Id.
   */
  folderId?: string;
  /**
   * Optional. User Id.
   */
  userId?: string;
  /**
   * Optional. The record index to start at. All items with a lower index will be dropped from the results.
   */
  startIndex?: number;
  /**
   * Optional. The maximum number of records to return.
   */
  limit?: number;
  /**
   * Optional. Sort Order - Ascending,Descending.
   */
  sortOrder?: SortOrder[];
  /**
   * Optional. Specify additional filters to apply.
   */
  filters?: ItemFilter[];
  /**
   * Optional. Specify one or more sort orders, comma delimited. Options: Album, AlbumArtist, Artist, Budget, CommunityRating, CriticRating, DateCreated, DatePlayed, PlayCount, PremiereDate, ProductionYear, SortName, Random, Revenue, Runtime.
   */
  sortBy?: string[];
  /**
   * Optional. Specify additional fields of information to return in the output.
   */
  fields?: ItemFields[];
};
