/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type GetDirectoryContentsParams = {
  /**
   * The path.
   */
  path: string;
  /**
   * An optional filter to include or exclude files from the results. true/false.
   */
  includeFiles?: boolean;
  /**
   * An optional filter to include or exclude folders from the results. true/false.
   */
  includeDirectories?: boolean;
};
