/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type GetDevicesParams = {
  /**
   * Gets or sets a value indicating whether [supports synchronize].
   */
  supportsSync?: boolean;
  /**
   * Gets or sets the user identifier.
   */
  userId?: string;
};
