/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ItemFields } from "./itemFields";
import type { ImageType } from "./imageType";

export type GetEpisodesParams = {
  userId?: string;
  fields?: ItemFields[];
  season?: number;
  seasonId?: string;
  isMissing?: boolean;
  adjacentTo?: string;
  startItemId?: string;
  startIndex?: number;
  limit?: number;
  enableImages?: boolean;
  imageTypeLimit?: number;
  enableImageTypes?: ImageType[];
  enableUserData?: boolean;
  sortBy?: string;
};
