/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ItemFields } from "./itemFields";
import type { ImageType } from "./imageType";

export type GetEpisodesParams = {
  /**
   * The user id.
   */
  userId?: string;
  /**
   * Optional. Specify additional fields of information to return in the output. This allows multiple, comma delimited. Options: Budget, Chapters, DateCreated, Genres, HomePageUrl, IndexOptions, MediaStreams, Overview, ParentId, Path, People, ProviderIds, PrimaryImageAspectRatio, Revenue, SortName, Studios, Taglines, TrailerUrls.
   */
  fields?: ItemFields[];
  /**
   * Optional filter by season number.
   */
  season?: number;
  /**
   * Optional. Filter by season id.
   */
  seasonId?: string;
  /**
   * Optional. Filter by items that are missing episodes or not.
   */
  isMissing?: boolean;
  /**
   * Optional. Return items that are siblings of a supplied item.
   */
  adjacentTo?: string;
  /**
   * Optional. Skip through the list until a given item is found.
   */
  startItemId?: string;
  /**
   * Optional. The record index to start at. All items with a lower index will be dropped from the results.
   */
  startIndex?: number;
  /**
   * Optional. The maximum number of records to return.
   */
  limit?: number;
  /**
   * Optional, include image information in output.
   */
  enableImages?: boolean;
  /**
   * Optional, the max number of images to return, per image type.
   */
  imageTypeLimit?: number;
  /**
   * Optional. The image types to include in the output.
   */
  enableImageTypes?: ImageType[];
  /**
   * Optional. Include user data.
   */
  enableUserData?: boolean;
  /**
   * Optional. Specify one or more sort orders, comma delimited. Options: Album, AlbumArtist, Artist, Budget, CommunityRating, CriticRating, DateCreated, DatePlayed, PlayCount, PremiereDate, ProductionYear, SortName, Random, Revenue, Runtime.
   */
  sortBy?: string;
};
