/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type GetItemCountsParams = {
  /**
   * Optional. Get counts from a specific user's library.
   */
  userId?: string;
  /**
   * Optional. Get counts of favorite items.
   */
  isFavorite?: boolean;
};
