/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ItemFields } from "./itemFields";
import type { BaseItemKind } from "./baseItemKind";
import type { ImageType } from "./imageType";

export type GetLatestMediaParams = {
  /**
   * Specify this to localize the search to a specific item or folder. Omit to use the root.
   */
  parentId?: string;
  /**
   * Optional. Specify additional fields of information to return in the output.
   */
  fields?: ItemFields[];
  /**
   * Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited.
   */
  includeItemTypes?: BaseItemKind[];
  /**
   * Filter by items that are played, or not.
   */
  isPlayed?: boolean;
  /**
   * Optional. include image information in output.
   */
  enableImages?: boolean;
  /**
   * Optional. the max number of images to return, per image type.
   */
  imageTypeLimit?: number;
  /**
   * Optional. The image types to include in the output.
   */
  enableImageTypes?: ImageType[];
  /**
   * Optional. include user data.
   */
  enableUserData?: boolean;
  /**
   * Return item limit.
   */
  limit?: number;
  /**
   * Whether or not to group items into a parent container.
   */
  groupItems?: boolean;
};
