/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ChannelType } from "./channelType";
import type { ImageType } from "./imageType";
import type { ItemFields } from "./itemFields";
import type { SortOrder } from "./sortOrder";

export type GetLiveTvChannelsParams = {
  /**
   * Optional. Filter by channel type.
   */
  type?: ChannelType;
  /**
   * Optional. Filter by user and attach user data.
   */
  userId?: string;
  /**
   * Optional. The record index to start at. All items with a lower index will be dropped from the results.
   */
  startIndex?: number;
  /**
   * Optional. Filter for movies.
   */
  isMovie?: boolean;
  /**
   * Optional. Filter for series.
   */
  isSeries?: boolean;
  /**
   * Optional. Filter for news.
   */
  isNews?: boolean;
  /**
   * Optional. Filter for kids.
   */
  isKids?: boolean;
  /**
   * Optional. Filter for sports.
   */
  isSports?: boolean;
  /**
   * Optional. The maximum number of records to return.
   */
  limit?: number;
  /**
   * Optional. Filter by channels that are favorites, or not.
   */
  isFavorite?: boolean;
  /**
   * Optional. Filter by channels that are liked, or not.
   */
  isLiked?: boolean;
  /**
   * Optional. Filter by channels that are disliked, or not.
   */
  isDisliked?: boolean;
  /**
   * Optional. Include image information in output.
   */
  enableImages?: boolean;
  /**
   * Optional. The max number of images to return, per image type.
   */
  imageTypeLimit?: number;
  /**
   * "Optional. The image types to include in the output.
   */
  enableImageTypes?: ImageType[];
  /**
   * Optional. Specify additional fields of information to return in the output.
   */
  fields?: ItemFields[];
  /**
   * Optional. Include user data.
   */
  enableUserData?: boolean;
  /**
   * Optional. Key to sort by.
   */
  sortBy?: string[];
  /**
   * Optional. Sort order.
   */
  sortOrder?: SortOrder;
  /**
   * Optional. Incorporate favorite and like status into channel sorting.
   */
  enableFavoriteSorting?: boolean;
  /**
   * Optional. Adds current program info to each channel.
   */
  addCurrentProgram?: boolean;
};
