/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type GetLineupsParams = {
  /**
   * Provider id.
   */
  id?: string;
  /**
   * Provider type.
   */
  type?: string;
  /**
   * Location.
   */
  location?: string;
  /**
   * Country.
   */
  country?: string;
};
