/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { BaseItemKind } from "./baseItemKind";

export type GetQueryFiltersLegacyParams = {
  userId?: string;
  parentId?: string;
  includeItemTypes?: BaseItemKind[];
  mediaTypes?: string[];
};
