/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { BaseItemKind } from "./baseItemKind";

export type GetQueryFiltersParams = {
  /**
   * Optional. User id.
   */
  userId?: string;
  /**
   * Optional. Specify this to localize the search to a specific item or folder. Omit to use the root.
   */
  parentId?: string;
  /**
   * Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited.
   */
  includeItemTypes?: BaseItemKind[];
  /**
   * Optional. Is item airing.
   */
  isAiring?: boolean;
  /**
   * Optional. Is item movie.
   */
  isMovie?: boolean;
  /**
   * Optional. Is item sports.
   */
  isSports?: boolean;
  /**
   * Optional. Is item kids.
   */
  isKids?: boolean;
  /**
   * Optional. Is item news.
   */
  isNews?: boolean;
  /**
   * Optional. Is item series.
   */
  isSeries?: boolean;
  /**
   * Optional. Search recursive.
   */
  recursive?: boolean;
};
