/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ImageType } from "./imageType";

export type GetRemoteImagesParams = {
  type?: ImageType;
  startIndex?: number;
  limit?: number;
  providerName?: string;
  includeAllLanguages?: boolean;
};
