/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ImageType } from "./imageType";
import type { ItemFields } from "./itemFields";

export type GetRecommendedProgramsParams = {
  /**
   * Optional. filter by user id.
   */
  userId?: string;
  /**
   * Optional. The maximum number of records to return.
   */
  limit?: number;
  /**
   * Optional. Filter by programs that are currently airing, or not.
   */
  isAiring?: boolean;
  /**
   * Optional. Filter by programs that have completed airing, or not.
   */
  hasAired?: boolean;
  /**
   * Optional. Filter for series.
   */
  isSeries?: boolean;
  /**
   * Optional. Filter for movies.
   */
  isMovie?: boolean;
  /**
   * Optional. Filter for news.
   */
  isNews?: boolean;
  /**
   * Optional. Filter for kids.
   */
  isKids?: boolean;
  /**
   * Optional. Filter for sports.
   */
  isSports?: boolean;
  /**
   * Optional. Include image information in output.
   */
  enableImages?: boolean;
  /**
   * Optional. The max number of images to return, per image type.
   */
  imageTypeLimit?: number;
  /**
   * Optional. The image types to include in the output.
   */
  enableImageTypes?: ImageType[];
  /**
   * The genres to return guide information for.
   */
  genreIds?: string[];
  /**
   * Optional. Specify additional fields of information to return in the output.
   */
  fields?: ItemFields[];
  /**
   * Optional. include user data.
   */
  enableUserData?: boolean;
  /**
   * Retrieve total record count.
   */
  enableTotalRecordCount?: boolean;
};
