/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ItemFields } from "./itemFields";
import type { ImageType } from "./imageType";
import type { BaseItemKind } from "./baseItemKind";

export type GetResumeItemsParams = {
  /**
   * The start index.
   */
  startIndex?: number;
  /**
   * The item limit.
   */
  limit?: number;
  /**
   * The search term.
   */
  searchTerm?: string;
  /**
   * Specify this to localize the search to a specific item or folder. Omit to use the root.
   */
  parentId?: string;
  /**
   * Optional. Specify additional fields of information to return in the output. This allows multiple, comma delimited. Options: Budget, Chapters, DateCreated, Genres, HomePageUrl, IndexOptions, MediaStreams, Overview, ParentId, Path, People, ProviderIds, PrimaryImageAspectRatio, Revenue, SortName, Studios, Taglines.
   */
  fields?: ItemFields[];
  /**
   * Optional. Filter by MediaType. Allows multiple, comma delimited.
   */
  mediaTypes?: string[];
  /**
   * Optional. Include user data.
   */
  enableUserData?: boolean;
  /**
   * Optional. The max number of images to return, per image type.
   */
  imageTypeLimit?: number;
  /**
   * Optional. The image types to include in the output.
   */
  enableImageTypes?: ImageType[];
  /**
   * Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited.
   */
  excludeItemTypes?: BaseItemKind[];
  /**
   * Optional. If specified, results will be filtered based on the item type. This allows multiple, comma delimited.
   */
  includeItemTypes?: BaseItemKind[];
  /**
   * Optional. Enable the total record count.
   */
  enableTotalRecordCount?: boolean;
  /**
   * Optional. Include image information in output.
   */
  enableImages?: boolean;
  /**
   * Optional. Whether to exclude the currently active sessions.
   */
  excludeActiveSessions?: boolean;
};
