/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ImageFormat } from "./imageFormat";

export type GetSplashscreenParams = {
  /**
   * Supply the cache tag from the item object to receive strong caching headers.
   */
  tag?: string;
  /**
   * Determines the output format of the image - original,gif,jpg,png.
   */
  format?: ImageFormat;
  /**
   * The maximum image width to return.
   */
  maxWidth?: number;
  /**
   * The maximum image height to return.
   */
  maxHeight?: number;
  /**
   * The fixed image width to return.
   */
  width?: number;
  /**
   * The fixed image height to return.
   */
  height?: number;
  /**
   * Width of box to fill.
   */
  fillWidth?: number;
  /**
   * Height of box to fill.
   */
  fillHeight?: number;
  /**
   * Blur image.
   */
  blur?: number;
  /**
   * Apply a background color for transparent images.
   */
  backgroundColor?: string;
  /**
   * Apply a foreground layer on top of the image.
   */
  foregroundLayer?: string;
  /**
   * Quality setting, from 0-100.
   */
  quality?: number;
};
