/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type GetSubtitleParams = { itemId?: string; mediaSourceId?: string; index?: number; format?: string; endPositionTicks?: number; copyTimestamps?: boolean; addVttTimeMap?: boolean; startPositionTicks?: number };
