/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type GetTimersParams = {
  /**
   * Optional. Filter by channel id.
   */
  channelId?: string;
  /**
   * Optional. Filter by timers belonging to a series timer.
   */
  seriesTimerId?: string;
  /**
   * Optional. Filter by timers that are active.
   */
  isActive?: boolean;
  /**
   * Optional. Filter by timers that are scheduled.
   */
  isScheduled?: boolean;
};
