/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type GetUserViewsParams = {
  /**
   * Whether or not to include external views such as channels or live tv.
   */
  includeExternalContent?: boolean;
  /**
   * Preset views.
   */
  presetViews?: string[];
  /**
   * Whether or not to include hidden content.
   */
  includeHidden?: boolean;
};
