/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface GuideInfo {
  /** Gets or sets the end date. */
  EndDate?: string;
  /** Gets or sets the start date. */
  StartDate?: string;
}
