/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type HeaderMatchType =
  (typeof HeaderMatchType)[keyof typeof HeaderMatchType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HeaderMatchType = {
  Equals: "Equals",
  Regex: "Regex",
  Substring: "Substring",
} as const;
