/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ImageType } from "./imageType";

/**
 * Class ImageInfo.
 */
export interface ImageInfo {
  /** Gets or sets the type of the image. */
  ImageType?: ImageType;
  /** Gets or sets the index of the image. */
  ImageIndex?: number | null;
  /** Gets or sets the image tag. */
  ImageTag?: string | null;
  /** Gets or sets the path. */
  Path?: string | null;
  /** Gets or sets the blurhash. */
  BlurHash?: string | null;
  /** Gets or sets the height. */
  Height?: number | null;
  /** Gets or sets the width. */
  Width?: number | null;
  /** Gets or sets the size. */
  Size?: number;
}
