/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface ImageByNameInfo {
  /**
   * Gets or sets the context.
   * @nullable
   */
  Context?: string | null;
  /** Gets or sets the length of the file. */
  FileLength?: number;
  /**
   * Gets or sets the format.
   * @nullable
   */
  Format?: string | null;
  /**
   * Gets or sets the name.
   * @nullable
   */
  Name?: string | null;
  /**
   * Gets or sets the theme.
   * @nullable
   */
  Theme?: string | null;
}
