/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type ImageOrientation =
  (typeof ImageOrientation)[keyof typeof ImageOrientation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageOrientation = {
  TopLeft: "TopLeft",
  TopRight: "TopRight",
  BottomRight: "BottomRight",
  BottomLeft: "BottomLeft",
  LeftTop: "LeftTop",
  RightTop: "RightTop",
  RightBottom: "RightBottom",
  LeftBottom: "LeftBottom",
} as const;
