/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ImageType } from "./imageType";

export interface ImageOption {
  /** Gets or sets the limit. */
  Limit?: number;
  /** Gets or sets the minimum width. */
  MinWidth?: number;
  /** Gets or sets the type. */
  Type?: ImageType;
}
