/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface ImageByNameInfo {
  /** Gets or sets the name. */
  Name?: string | null;
  /** Gets or sets the theme. */
  Theme?: string | null;
  /** Gets or sets the context. */
  Context?: string | null;
  /** Gets or sets the length of the file. */
  FileLength?: number;
  /** Gets or sets the format. */
  Format?: string | null;
}
