/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type InstallPackageParams = {
  /**
   * GUID of the associated assembly.
   */
  assemblyGuid?: string;
  /**
   * Optional version. Defaults to latest version.
   */
  version?: string;
  /**
   * Optional. Specify the repository to install from.
   */
  repositoryUrl?: string;
};
