/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PackageInfo } from "./packageInfo";

/**
 * Gets or sets package information for the installation.
 * @nullable
 */
export type InstallationInfoPackageInfo = PackageInfo | null;
