/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Defines the MediaBrowser.Common.Plugins.IPlugin.
 */
export interface IPlugin {
  /** Gets the name of the plugin. */
  readonly Name?: string | null;
  /** Gets the Description. */
  readonly Description?: string | null;
  /** Gets the unique id. */
  readonly Id?: string;
  /** Gets the plugin version. */
  readonly Version?: string | null;
  /** Gets the path to the assembly file. */
  readonly AssemblyFilePath?: string | null;
  /** Gets a value indicating whether the plugin can be uninstalled. */
  readonly CanUninstall?: boolean;
  /** Gets the full path to the data folder, where the plugin can store any miscellaneous files needed. */
  readonly DataFolderPath?: string | null;
}
