/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class LibrarySummary.
 */
export interface ItemCounts {
  /** Gets or sets the album count. */
  AlbumCount?: number;
  /** Gets or sets the artist count. */
  ArtistCount?: number;
  /** Gets or sets the book count. */
  BookCount?: number;
  /** Gets or sets the box set count. */
  BoxSetCount?: number;
  /** Gets or sets the episode count. */
  EpisodeCount?: number;
  /** Gets or sets the item count. */
  ItemCount?: number;
  /** Gets or sets the movie count. */
  MovieCount?: number;
  /** Gets or sets the music video count. */
  MusicVideoCount?: number;
  /** Gets or sets the program count. */
  ProgramCount?: number;
  /** Gets or sets the series count. */
  SeriesCount?: number;
  /** Gets or sets the song count. */
  SongCount?: number;
  /** Gets or sets the trailer count. */
  TrailerCount?: number;
}
