/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Enum ItemFilter.
 */
export type ItemFilter = (typeof ItemFilter)[keyof typeof ItemFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemFilter = {
  IsFolder: "IsFolder",
  IsNotFolder: "IsNotFolder",
  IsUnplayed: "IsUnplayed",
  IsPlayed: "IsPlayed",
  IsFavorite: "IsFavorite",
  IsResumable: "IsResumable",
  Likes: "Likes",
  Dislikes: "Dislikes",
  IsFavoriteOrLikes: "IsFavoriteOrLikes",
} as const;
