/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class JoinGroupRequestDto.
 */
export interface JoinGroupRequestDto {
  /** Gets or sets the group identifier. */
  GroupId?: string;
}
