/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type KeepUntil = (typeof KeepUntil)[keyof typeof KeepUntil];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KeepUntil = {
  UntilDeleted: "UntilDeleted",
  UntilSpaceNeeded: "UntilSpaceNeeded",
  UntilWatched: "UntilWatched",
  UntilDate: "UntilDate",
} as const;
