/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { EmbeddedSubtitleOptions } from "./embeddedSubtitleOptions";
import type { MediaPathInfo } from "./mediaPathInfo";
import type { TypeOptions } from "./typeOptions";

export interface LibraryOptions {
  /** An enum representing the options to disable embedded subs. */
  AllowEmbeddedSubtitles?: EmbeddedSubtitleOptions;
  AutomaticallyAddToCollection?: boolean;
  AutomaticRefreshIntervalDays?: number;
  DisabledLocalMetadataReaders?: string[];
  DisabledSubtitleFetchers?: string[];
  EnableAutomaticSeriesGrouping?: boolean;
  EnableChapterImageExtraction?: boolean;
  EnableEmbeddedEpisodeInfos?: boolean;
  EnableEmbeddedTitles?: boolean;
  /** @deprecated */
  EnableInternetProviders?: boolean;
  EnablePhotos?: boolean;
  EnableRealtimeMonitor?: boolean;
  ExtractChapterImagesDuringLibraryScan?: boolean;
  /** @nullable */
  LocalMetadataReaderOrder?: string[] | null;
  /**
   * Gets or sets the metadata country code.
   * @nullable
   */
  MetadataCountryCode?: string | null;
  /** @nullable */
  MetadataSavers?: string[] | null;
  PathInfos?: MediaPathInfo[];
  /**
   * Gets or sets the preferred metadata language.
   * @nullable
   */
  PreferredMetadataLanguage?: string | null;
  RequirePerfectSubtitleMatch?: boolean;
  SaveLocalMetadata?: boolean;
  SaveSubtitlesWithMedia?: boolean;
  SeasonZeroDisplayName?: string;
  SkipSubtitlesIfAudioTrackMatches?: boolean;
  SkipSubtitlesIfEmbeddedSubtitlesPresent?: boolean;
  /** @nullable */
  SubtitleDownloadLanguages?: string[] | null;
  SubtitleFetcherOrder?: string[];
  TypeOptions?: TypeOptions[];
}
