/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Library option info dto.
 */
export interface LibraryOptionInfoDto {
  /** Gets or sets name. */
  Name?: string | null;
  /** Gets or sets a value indicating whether default enabled. */
  DefaultEnabled?: boolean;
}
