/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { MediaPathInfo } from "./mediaPathInfo";
import type { EmbeddedSubtitleOptions } from "./embeddedSubtitleOptions";
import type { TypeOptions } from "./typeOptions";

export interface LibraryOptions {
  EnablePhotos?: boolean;
  EnableRealtimeMonitor?: boolean;
  EnableChapterImageExtraction?: boolean;
  ExtractChapterImagesDuringLibraryScan?: boolean;
  PathInfos?: MediaPathInfo[];
  SaveLocalMetadata?: boolean;
  /** @deprecated */
  EnableInternetProviders?: boolean;
  EnableAutomaticSeriesGrouping?: boolean;
  EnableEmbeddedTitles?: boolean;
  EnableEmbeddedEpisodeInfos?: boolean;
  AutomaticRefreshIntervalDays?: number;
  /** Gets or sets the preferred metadata language. */
  PreferredMetadataLanguage?: string | null;
  /** Gets or sets the metadata country code. */
  MetadataCountryCode?: string | null;
  SeasonZeroDisplayName?: string;
  MetadataSavers?: string[] | null;
  DisabledLocalMetadataReaders?: string[];
  LocalMetadataReaderOrder?: string[] | null;
  DisabledSubtitleFetchers?: string[];
  SubtitleFetcherOrder?: string[];
  SkipSubtitlesIfEmbeddedSubtitlesPresent?: boolean;
  SkipSubtitlesIfAudioTrackMatches?: boolean;
  SubtitleDownloadLanguages?: string[] | null;
  RequirePerfectSubtitleMatch?: boolean;
  SaveSubtitlesWithMedia?: boolean;
  AutomaticallyAddToCollection?: boolean;
  /** An enum representing the options to disable embedded subs. */
  AllowEmbeddedSubtitles?: EmbeddedSubtitleOptions;
  TypeOptions?: TypeOptions[];
}
