/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { LiveTvServiceInfo } from "./liveTvServiceInfo";

export interface LiveTvInfo {
  /** Gets or sets the services. */
  Services?: LiveTvServiceInfo[];
  /** Gets or sets a value indicating whether this instance is enabled. */
  IsEnabled?: boolean;
  /** Gets or sets the enabled users. */
  EnabledUsers?: string[];
}
