/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface LocalizationOption {
  /** @nullable */
  Name?: string | null;
  /** @nullable */
  Value?: string | null;
}
