/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface LogFile {
  /** Gets or sets the date created. */
  DateCreated?: string;
  /** Gets or sets the date modified. */
  DateModified?: string;
  /** Gets or sets the size. */
  Size?: number;
  /** Gets or sets the name. */
  Name?: string | null;
}
