/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { MediaPathDtoPathInfo } from './mediaPathDtoPathInfo';

/**
 * Media Path dto.
 */
export interface MediaPathDto {
  /** Gets or sets the name of the library. */
  Name: string;
  /** Gets or sets the path to add. */
  Path?: string | null;
  /** Gets or sets the path info. */
  PathInfo?: MediaPathDtoPathInfo;
}
