/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class MediaAttachment.
 */
export interface MediaAttachment {
  /**
   * Gets or sets the codec.
   * @nullable
   */
  Codec?: string | null;
  /**
   * Gets or sets the codec tag.
   * @nullable
   */
  CodecTag?: string | null;
  /**
   * Gets or sets the comment.
   * @nullable
   */
  Comment?: string | null;
  /**
   * Gets or sets the delivery URL.
   * @nullable
   */
  DeliveryUrl?: string | null;
  /**
   * Gets or sets the filename.
   * @nullable
   */
  FileName?: string | null;
  /** Gets or sets the index. */
  Index?: number;
  /**
   * Gets or sets the MIME type.
   * @nullable
   */
  MimeType?: string | null;
}
