/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class MediaAttachment.
 */
export interface MediaAttachment {
  /** Gets or sets the codec. */
  Codec?: string | null;
  /** Gets or sets the codec tag. */
  CodecTag?: string | null;
  /** Gets or sets the comment. */
  Comment?: string | null;
  /** Gets or sets the index. */
  Index?: number;
  /** Gets or sets the filename. */
  FileName?: string | null;
  /** Gets or sets the MIME type. */
  MimeType?: string | null;
  /** Gets or sets the delivery URL. */
  DeliveryUrl?: string | null;
}
