/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * The media update info path.
 */
export interface MediaUpdateInfoPathDto {
  /** Gets or sets media path. */
  Path?: string | null;
  /** Gets or sets media update type.
Created, Modified, Deleted. */
  UpdateType?: string | null;
}
