/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type MediaSourceType =
  (typeof MediaSourceType)[keyof typeof MediaSourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaSourceType = {
  Default: "Default",
  Grouping: "Grouping",
  Placeholder: "Placeholder",
} as const;
