/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { Video3DFormat } from "./video3DFormat";

export type MediaSourceInfoVideo3DFormat = Video3DFormat | null;
