/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface MessageCommand {
  /** @nullable */
  Header?: string | null;
  Text: string;
  /** @nullable */
  TimeoutMs?: number | null;
}
