/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class MetadataOptions.
 */
export interface MetadataOptions {
  /** @nullable */
  DisabledImageFetchers?: string[] | null;
  /** @nullable */
  DisabledMetadataFetchers?: string[] | null;
  /** @nullable */
  DisabledMetadataSavers?: string[] | null;
  /** @nullable */
  ImageFetcherOrder?: string[] | null;
  /** @nullable */
  ItemType?: string | null;
  /** @nullable */
  LocalMetadataReaderOrder?: string[] | null;
  /** @nullable */
  MetadataFetcherOrder?: string[] | null;
}
