/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Enum MetadataFields.
 */
export type MetadataField = (typeof MetadataField)[keyof typeof MetadataField];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetadataField = {
  Cast: "Cast",
  Genres: "Genres",
  ProductionLocations: "ProductionLocations",
  Studios: "Studios",
  Tags: "Tags",
  Name: "Name",
  Overview: "Overview",
  Runtime: "Runtime",
  OfficialRating: "OfficialRating",
} as const;
