/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class MetadataOptions.
 */
export interface MetadataOptions {
  ItemType?: string | null;
  DisabledMetadataSavers?: string[] | null;
  LocalMetadataReaderOrder?: string[] | null;
  DisabledMetadataFetchers?: string[] | null;
  MetadataFetcherOrder?: string[] | null;
  DisabledImageFetchers?: string[] | null;
  ImageFetcherOrder?: string[] | null;
}
