/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface NameValuePair {
  /**
   * Gets or sets the name.
   * @nullable
   */
  Name?: string | null;
  /**
   * Gets or sets the value.
   * @nullable
   */
  Value?: string | null;
}
