/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface NotificationTypeInfo {
  /** @nullable */
  Category?: string | null;
  Enabled?: boolean;
  IsBasedOnUserEvent?: boolean;
  /** @nullable */
  Name?: string | null;
  /** @nullable */
  Type?: string | null;
}
