/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { NotificationDto } from "./notificationDto";

/**
 * A list of notifications with the total record count for pagination.
 */
export interface NotificationResultDto {
  /** Gets or sets the current page of notifications. */
  Notifications?: NotificationDto[];
  /** Gets or sets the total number of notifications. */
  TotalRecordCount?: number;
}
