/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface NotificationTypeInfo {
  Type?: string | null;
  Name?: string | null;
  Enabled?: boolean;
  Category?: string | null;
  IsBasedOnUserEvent?: boolean;
}
