/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { NotificationLevel } from './notificationLevel';

/**
 * Gets or sets the maximum unread notification level.
 */
export type NotificationsSummaryDtoMaxUnreadNotificationLevel = NotificationLevel | null;
