/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type OnPlaybackStoppedParams = {
  /**
   * The id of the MediaSource.
   */
  mediaSourceId?: string;
  /**
   * The next media type that will play.
   */
  nextMediaType?: string;
  /**
   * Optional. The position, in ticks, where playback stopped. 1 tick = 10000 ms.
   */
  positionTicks?: number;
  /**
   * The live stream id.
   */
  liveStreamId?: string;
  /**
   * The play session id.
   */
  playSessionId?: string;
};
