/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlayMethod } from "./playMethod";
import type { RepeatMode } from "./repeatMode";

export type OnPlaybackProgressParams = {
  mediaSourceId?: string;
  positionTicks?: number;
  audioStreamIndex?: number;
  subtitleStreamIndex?: number;
  volumeLevel?: number;
  playMethod?: PlayMethod;
  liveStreamId?: string;
  playSessionId?: string;
  repeatMode?: RepeatMode;
  isPaused?: boolean;
  isMuted?: boolean;
};
