/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type OnPlaybackStoppedParams = {
  mediaSourceId?: string;
  nextMediaType?: string;
  positionTicks?: number;
  liveStreamId?: string;
  playSessionId?: string;
};
