/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type OpenLiveStreamParams = {
  /**
   * The open token.
   */
  openToken?: string;
  /**
   * The user id.
   */
  userId?: string;
  /**
   * The play session id.
   */
  playSessionId?: string;
  /**
   * The maximum streaming bitrate.
   */
  maxStreamingBitrate?: number;
  /**
   * The start time in ticks.
   */
  startTimeTicks?: number;
  /**
   * The audio stream index.
   */
  audioStreamIndex?: number;
  /**
   * The subtitle stream index.
   */
  subtitleStreamIndex?: number;
  /**
   * The maximum number of audio channels.
   */
  maxAudioChannels?: number;
  /**
   * The item id.
   */
  itemId?: string;
  /**
   * Whether to enable direct play. Default: true.
   */
  enableDirectPlay?: boolean;
  /**
   * Whether to enable direct stream. Default: true.
   */
  enableDirectStream?: boolean;
};
