/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class ParentalRating.
 */
export interface ParentalRating {
  /** Gets or sets the name. */
  Name?: string | null;
  /** Gets or sets the value. */
  Value?: number;
}
