/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Gets or sets the provider ids.
 */
export type PersonLookupInfoProviderIds = {[key: string]: string | null} | null;
