/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class PingRequestDto.
 */
export interface PingRequestDto {
  /** Gets or sets the ping time. */
  Ping?: number;
}
