/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface PinRedeemResult {
  /** Gets or sets a value indicating whether this MediaBrowser.Model.Users.PinRedeemResult is success. */
  Success?: boolean;
  /** Gets or sets the users reset. */
  UsersReset?: string[];
}
