/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlaybackProgressInfoItem } from "./playbackProgressInfoItem";
import type { QueueItem } from "./queueItem";
import type { PlayMethod } from "./playMethod";
import type { RepeatMode } from "./repeatMode";

/**
 * Class PlaybackProgressInfo.
 */
export interface PlaybackProgressInfo {
  /** @nullable */
  AspectRatio?: string | null;
  /**
   * Gets or sets the index of the audio stream.
   * @nullable
   */
  AudioStreamIndex?: number | null;
  /** @nullable */
  Brightness?: number | null;
  /** Gets or sets a value indicating whether this instance can seek. */
  CanSeek?: boolean;
  /** Gets or sets a value indicating whether this instance is muted. */
  IsMuted?: boolean;
  /** Gets or sets a value indicating whether this instance is paused. */
  IsPaused?: boolean;
  /**
   * Gets or sets the item.
   * @nullable
   */
  Item?: PlaybackProgressInfoItem;
  /** Gets or sets the item identifier. */
  ItemId?: string;
  /**
   * Gets or sets the live stream identifier.
   * @nullable
   */
  LiveStreamId?: string | null;
  /**
   * Gets or sets the media version identifier.
   * @nullable
   */
  MediaSourceId?: string | null;
  /** @nullable */
  NowPlayingQueue?: QueueItem[] | null;
  /** @nullable */
  PlaybackStartTimeTicks?: number | null;
  /** @nullable */
  PlaylistItemId?: string | null;
  /** Gets or sets the play method. */
  PlayMethod?: PlayMethod;
  /**
   * Gets or sets the play session identifier.
   * @nullable
   */
  PlaySessionId?: string | null;
  /**
   * Gets or sets the position ticks.
   * @nullable
   */
  PositionTicks?: number | null;
  /** Gets or sets the repeat mode. */
  RepeatMode?: RepeatMode;
  /**
   * Gets or sets the session id.
   * @nullable
   */
  SessionId?: string | null;
  /**
   * Gets or sets the index of the subtitle stream.
   * @nullable
   */
  SubtitleStreamIndex?: number | null;
  /**
   * Gets or sets the volume level.
   * @nullable
   */
  VolumeLevel?: number | null;
}
