/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlaystateCommand } from "./playstateCommand";

export interface PlaystateRequest {
  /** Enum PlaystateCommand. */
  Command?: PlaystateCommand;
  /**
   * Gets or sets the controlling user identifier.
   * @nullable
   */
  ControllingUserId?: string | null;
  /** @nullable */
  SeekPositionTicks?: number | null;
}
