/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlayCommand } from "./playCommand";

/**
 * Class PlayRequest.
 */
export interface PlayRequest {
  /** @nullable */
  AudioStreamIndex?: number | null;
  /** Gets or sets the controlling user identifier. */
  ControllingUserId?: string;
  /**
   * Gets or sets the item ids.
   * @nullable
   */
  ItemIds?: string[] | null;
  /** @nullable */
  MediaSourceId?: string | null;
  /** Gets or sets the play command. */
  PlayCommand?: PlayCommand;
  /** @nullable */
  StartIndex?: number | null;
  /**
   * Gets or sets the start position ticks that the first item should be played at.
   * @nullable
   */
  StartPositionTicks?: number | null;
  /** @nullable */
  SubtitleStreamIndex?: number | null;
}
