/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlaybackErrorCode } from "./playbackErrorCode";

/**
 * Gets or sets the error code.
 * @nullable
 */
export type PlaybackInfoResponseErrorCode = PlaybackErrorCode | null;
