/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { DeviceProfile } from "./deviceProfile";

/**
 * Gets or sets the device profile.
 * @nullable
 */
export type PlaybackInfoDtoDeviceProfile = DeviceProfile | null;
