/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Enum PlayCommand.
 */
export type PlayCommand = typeof PlayCommand[keyof typeof PlayCommand];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayCommand = {
  PlayNow: 'PlayNow',
  PlayNext: 'PlayNext',
  PlayLast: 'PlayLast',
  PlayInstantMix: 'PlayInstantMix',
  PlayShuffle: 'PlayShuffle',
} as const;
