/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlayCommand } from './playCommand';

export type PlayParams = { playCommand: PlayCommand; itemIds: string[]; startPositionTicks?: number; mediaSourceId?: string; audioStreamIndex?: number; subtitleStreamIndex?: number; startIndex?: number };
