/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlaystateCommand } from "./playstateCommand";

export interface PlaystateRequest {
  /** Enum PlaystateCommand. */
  Command?: PlaystateCommand;
  SeekPositionTicks?: number | null;
  /** Gets or sets the controlling user identifier. */
  ControllingUserId?: string | null;
}
