/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { PlaybackStopInfoItem } from './playbackStopInfoItem';
import type { QueueItem } from './queueItem';

/**
 * Class PlaybackStopInfo.
 */
export interface PlaybackStopInfo {
  /** Gets or sets the item. */
  Item?: PlaybackStopInfoItem;
  /** Gets or sets the item identifier. */
  ItemId?: string;
  /** Gets or sets the session id. */
  SessionId?: string | null;
  /** Gets or sets the media version identifier. */
  MediaSourceId?: string | null;
  /** Gets or sets the position ticks. */
  PositionTicks?: number | null;
  /** Gets or sets the live stream identifier. */
  LiveStreamId?: string | null;
  /** Gets or sets the play session identifier. */
  PlaySessionId?: string | null;
  /** Gets or sets a value indicating whether this MediaBrowser.Model.Session.PlaybackStopInfo is failed. */
  Failed?: boolean;
  NextMediaType?: string | null;
  PlaylistItemId?: string | null;
  NowPlayingQueue?: QueueItem[] | null;
}
