/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type PlayAccess = typeof PlayAccess[keyof typeof PlayAccess];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayAccess = {
  Full: 'Full',
  None: 'None',
} as const;
