/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type PlaybackErrorCode =
  (typeof PlaybackErrorCode)[keyof typeof PlaybackErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlaybackErrorCode = {
  NotAllowed: "NotAllowed",
  NoCompatibleStream: "NoCompatibleStream",
  RateLimitExceeded: "RateLimitExceeded",
} as const;
