/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Plugin load status.
 */
export type PluginStatus = (typeof PluginStatus)[keyof typeof PluginStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PluginStatus = {
  Active: "Active",
  Restart: "Restart",
  Deleted: "Deleted",
  Superceded: "Superceded",
  Malfunctioned: "Malfunctioned",
  NotSupported: "NotSupported",
  Disabled: "Disabled",
} as const;
