/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { GeneralCommandType } from "./generalCommandType";

export type PostCapabilitiesParams = {
  /**
   * The session id.
   */
  id?: string;
  /**
   * A list of playable media types, comma delimited. Audio, Video, Book, Photo.
   */
  playableMediaTypes?: string[];
  /**
   * A list of supported remote control commands, comma delimited.
   */
  supportedCommands?: GeneralCommandType[];
  /**
   * Determines whether media can be played remotely..
   */
  supportsMediaControl?: boolean;
  /**
   * Determines whether sync is supported.
   */
  supportsSync?: boolean;
  /**
   * Determines whether the device supports a unique identifier.
   */
  supportsPersistentIdentifier?: boolean;
};
