/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type ProfileConditionValue = typeof ProfileConditionValue[keyof typeof ProfileConditionValue];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileConditionValue = {
  AudioChannels: 'AudioChannels',
  AudioBitrate: 'AudioBitrate',
  AudioProfile: 'AudioProfile',
  Width: 'Width',
  Height: 'Height',
  Has64BitOffsets: 'Has64BitOffsets',
  PacketLength: 'PacketLength',
  VideoBitDepth: 'VideoBitDepth',
  VideoBitrate: 'VideoBitrate',
  VideoFramerate: 'VideoFramerate',
  VideoLevel: 'VideoLevel',
  VideoProfile: 'VideoProfile',
  VideoTimestamp: 'VideoTimestamp',
  IsAnamorphic: 'IsAnamorphic',
  RefFrames: 'RefFrames',
  NumAudioStreams: 'NumAudioStreams',
  NumVideoStreams: 'NumVideoStreams',
  IsSecondaryAudio: 'IsSecondaryAudio',
  VideoCodecTag: 'VideoCodecTag',
  IsAvc: 'IsAvc',
  IsInterlaced: 'IsInterlaced',
  AudioSampleRate: 'AudioSampleRate',
  AudioBitDepth: 'AudioBitDepth',
  VideoRangeType: 'VideoRangeType',
} as const;
