/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ProfileConditionType } from "./profileConditionType";
import type { ProfileConditionValue } from "./profileConditionValue";

export interface ProfileCondition {
  Condition?: ProfileConditionType;
  Property?: ProfileConditionValue;
  Value?: string | null;
  IsRequired?: boolean;
}
