/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type ProgramAudio = (typeof ProgramAudio)[keyof typeof ProgramAudio];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProgramAudio = {
  Mono: "Mono",
  Stereo: "Stereo",
  Dolby: "Dolby",
  DolbyDigital: "DolbyDigital",
  Thx: "Thx",
  Atmos: "Atmos",
} as const;
