/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface PublicSystemInfo {
  /** Gets or sets the local address. */
  LocalAddress?: string | null;
  /** Gets or sets the name of the server. */
  ServerName?: string | null;
  /** Gets or sets the server version. */
  Version?: string | null;
  /** Gets or sets the product name. This is the AssemblyProduct name. */
  ProductName?: string | null;
  /** Gets or sets the operating system. */
  OperatingSystem?: string | null;
  /** Gets or sets the id. */
  Id?: string | null;
  /** Gets or sets a value indicating whether the startup wizard is completed. */
  StartupWizardCompleted?: boolean | null;
}
