/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface PublicSystemInfo {
  /**
   * Gets or sets the id.
   * @nullable
   */
  Id?: string | null;
  /**
   * Gets or sets the local address.
   * @nullable
   */
  LocalAddress?: string | null;
  /**
   * Gets or sets the operating system.
   * @nullable
   */
  OperatingSystem?: string | null;
  /**
   * Gets or sets the product name. This is the AssemblyProduct name.
   * @nullable
   */
  ProductName?: string | null;
  /**
   * Gets or sets the name of the server.
   * @nullable
   */
  ServerName?: string | null;
  /**
   * Gets or sets a value indicating whether the startup wizard is completed.
   * @nullable
   */
  StartupWizardCompleted?: boolean | null;
  /**
   * Gets or sets the server version.
   * @nullable
   */
  Version?: string | null;
}
