/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Stores the state of an quick connect request.
 */
export interface QuickConnectResult {
  /** Gets or sets a value indicating whether this request is authorized. */
  Authenticated?: boolean;
  /** Gets the secret value used to uniquely identify this request. Can be used to retrieve authentication information. */
  Secret?: string;
  /** Gets the user facing code used so the user can quickly differentiate this request from others. */
  Code?: string;
  /** Gets the requesting device id. */
  DeviceId?: string;
  /** Gets the requesting device name. */
  DeviceName?: string;
  /** Gets the requesting app name. */
  AppName?: string;
  /** Gets the requesting app version. */
  AppVersion?: string;
  /** Gets or sets the DateTime that this request was created. */
  DateAdded?: string;
}
