/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type RatingType = (typeof RatingType)[keyof typeof RatingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RatingType = {
  Score: "Score",
  Likes: "Likes",
} as const;
