/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class ReadyRequest.
 */
export interface ReadyRequestDto {
  /** Gets or sets a value indicating whether the client playback is unpaused. */
  IsPlaying?: boolean;
  /** Gets or sets the playlist item identifier of the playing item. */
  PlaylistItemId?: string;
  /** Gets or sets the position ticks. */
  PositionTicks?: number;
  /** Gets or sets when the request has been made by the client. */
  When?: string;
}
