/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { BaseItemDto } from "./baseItemDto";
import type { RecommendationType } from "./recommendationType";

export interface RecommendationDto {
  /** @nullable */
  BaselineItemName?: string | null;
  CategoryId?: string;
  /** @nullable */
  Items?: BaseItemDto[] | null;
  RecommendationType?: RecommendationType;
}
