/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { MetadataRefreshMode } from "./metadataRefreshMode";

export type RefreshItemParams = {
  /**
   * (Optional) Specifies the metadata refresh mode.
   */
  metadataRefreshMode?: MetadataRefreshMode;
  /**
   * (Optional) Specifies the image refresh mode.
   */
  imageRefreshMode?: MetadataRefreshMode;
  /**
   * (Optional) Determines if metadata should be replaced. Only applicable if mode is FullRefresh.
   */
  replaceAllMetadata?: boolean;
  /**
   * (Optional) Determines if images should be replaced. Only applicable if mode is FullRefresh.
   */
  replaceAllImages?: boolean;
};
