/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { MetadataRefreshMode } from "./metadataRefreshMode";

export type RefreshItemParams = {
  metadataRefreshMode?: MetadataRefreshMode;
  imageRefreshMode?: MetadataRefreshMode;
  replaceAllMetadata?: boolean;
  replaceAllImages?: boolean;
};
