/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export type RemoveVirtualFolderParams = {
  /**
   * The name of the folder.
   */
  name?: string;
  /**
   * Whether to refresh the library.
   */
  refreshLibrary?: boolean;
};
