/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * An enum representing the axis that should be scrolled.
 */
export type ScrollDirection =
  (typeof ScrollDirection)[keyof typeof ScrollDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScrollDirection = {
  Horizontal: "Horizontal",
  Vertical: "Vertical",
} as const;
