/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Enum SendCommandType.
 */
export type SendCommandType = typeof SendCommandType[keyof typeof SendCommandType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendCommandType = {
  Unpause: 'Unpause',
  Pause: 'Pause',
  Stop: 'Stop',
  Seek: 'Seek',
} as const;
