/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { DayPattern } from "./dayPattern";

/**
 * Gets or sets the day pattern.
 * @nullable
 */
export type SeriesTimerInfoDtoDayPattern = DayPattern | null;
