/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { DayPattern } from './dayPattern';

/**
 * Gets or sets the day pattern.
 */
export type SeriesTimerInfoDtoDayPattern = DayPattern | null;
