/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * The server discovery info model.
 */
export interface ServerDiscoveryInfo {
  /** Gets the address. */
  Address?: string;
  /** Gets the server identifier. */
  Id?: string;
  /** Gets the name. */
  Name?: string;
  /** Gets the endpoint address. */
  EndpointAddress?: string | null;
}
