/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { ClientCapabilities } from './clientCapabilities';

export type SessionInfoCapabilities = ClientCapabilities | null;
