/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class SessionUserInfo.
 */
export interface SessionUserInfo {
  /** Gets or sets the user identifier. */
  UserId?: string;
  /**
   * Gets or sets the name of the user.
   * @nullable
   */
  UserName?: string | null;
}
