/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { SessionUserInfo } from "./sessionUserInfo";
import type { SessionInfoCapabilities } from "./sessionInfoCapabilities";
import type { SessionInfoFullNowPlayingItem } from "./sessionInfoFullNowPlayingItem";
import type { SessionInfoNowPlayingItem } from "./sessionInfoNowPlayingItem";
import type { QueueItem } from "./queueItem";
import type { BaseItemDto } from "./baseItemDto";
import type { SessionInfoNowViewingItem } from "./sessionInfoNowViewingItem";
import type { SessionInfoPlayState } from "./sessionInfoPlayState";
import type { GeneralCommandType } from "./generalCommandType";
import type { SessionInfoTranscodingInfo } from "./sessionInfoTranscodingInfo";

/**
 * Class SessionInfo.
 */
export interface SessionInfo {
  /** @nullable */
  AdditionalUsers?: SessionUserInfo[] | null;
  /**
   * Gets or sets the application version.
   * @nullable
   */
  ApplicationVersion?: string | null;
  /** @nullable */
  Capabilities?: SessionInfoCapabilities;
  /**
   * Gets or sets the type of the client.
   * @nullable
   */
  Client?: string | null;
  /**
   * Gets or sets the device id.
   * @nullable
   */
  DeviceId?: string | null;
  /**
   * Gets or sets the name of the device.
   * @nullable
   */
  DeviceName?: string | null;
  /**
   * Gets or sets the type of the device.
   * @nullable
   */
  DeviceType?: string | null;
  /**
   * Class BaseItem.
   * @nullable
   */
  FullNowPlayingItem?: SessionInfoFullNowPlayingItem;
  HasCustomDeviceName?: boolean;
  /**
   * Gets or sets the id.
   * @nullable
   */
  Id?: string | null;
  /** Gets a value indicating whether this instance is active. */
  readonly IsActive?: boolean;
  /** Gets or sets the last activity date. */
  LastActivityDate?: string;
  /** Gets or sets the last playback check in. */
  LastPlaybackCheckIn?: string;
  /**
   * Gets or sets the now playing item.
   * @nullable
   */
  NowPlayingItem?: SessionInfoNowPlayingItem;
  /** @nullable */
  NowPlayingQueue?: QueueItem[] | null;
  /** @nullable */
  NowPlayingQueueFullItems?: BaseItemDto[] | null;
  /**
   * This is strictly used as a data transfer object from the api layer.
This holds information about a BaseItem in a format that is convenient for the client.
   * @nullable
   */
  NowViewingItem?: SessionInfoNowViewingItem;
  /**
   * Gets the playable media types.
   * @nullable
   */
  readonly PlayableMediaTypes?: readonly string[] | null;
  /** @nullable */
  PlaylistItemId?: string | null;
  /** @nullable */
  PlayState?: SessionInfoPlayState;
  /**
   * Gets or sets the remote end point.
   * @nullable
   */
  RemoteEndPoint?: string | null;
  /** @nullable */
  ServerId?: string | null;
  /**
   * Gets the supported commands.
   * @nullable
   */
  readonly SupportedCommands?: readonly GeneralCommandType[] | null;
  readonly SupportsMediaControl?: boolean;
  readonly SupportsRemoteControl?: boolean;
  /** @nullable */
  TranscodingInfo?: SessionInfoTranscodingInfo;
  /** Gets or sets the user id. */
  UserId?: string;
  /**
   * Gets or sets the username.
   * @nullable
   */
  UserName?: string | null;
  /** @nullable */
  UserPrimaryImageTag?: string | null;
}
