/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * The startup user DTO.
 */
export interface StartupUserDto {
  /** Gets or sets the username. */
  Name?: string | null;
  /** Gets or sets the user's password. */
  Password?: string | null;
}
