/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * The startup configuration DTO.
 */
export interface StartupConfigurationDto {
  /**
   * Gets or sets the metadata country code.
   * @nullable
   */
  MetadataCountryCode?: string | null;
  /**
   * Gets or sets the preferred language for the metadata.
   * @nullable
   */
  PreferredMetadataLanguage?: string | null;
  /**
   * Gets or sets UI language culture.
   * @nullable
   */
  UICulture?: string | null;
}
