/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface SubtitleOptions {
  DownloadEpisodeSubtitles?: boolean;
  /** @nullable */
  DownloadLanguages?: string[] | null;
  DownloadMovieSubtitles?: boolean;
  IsOpenSubtitleVipAccount?: boolean;
  /** @nullable */
  OpenSubtitlesPasswordHash?: string | null;
  /** @nullable */
  OpenSubtitlesUsername?: string | null;
  RequirePerfectMatch?: boolean;
  SkipIfAudioTrackMatches?: boolean;
  SkipIfEmbeddedSubtitlesPresent?: boolean;
}
