/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { TaskCompletionStatus } from "./taskCompletionStatus";

/**
 * Class TaskExecutionInfo.
 */
export interface TaskResult {
  /** Gets or sets the end time UTC. */
  EndTimeUtc?: string;
  /**
   * Gets or sets the error message.
   * @nullable
   */
  ErrorMessage?: string | null;
  /**
   * Gets or sets the id.
   * @nullable
   */
  Id?: string | null;
  /**
   * Gets or sets the key.
   * @nullable
   */
  Key?: string | null;
  /**
   * Gets or sets the long error message.
   * @nullable
   */
  LongErrorMessage?: string | null;
  /**
   * Gets or sets the name.
   * @nullable
   */
  Name?: string | null;
  /** Gets or sets the start time UTC. */
  StartTimeUtc?: string;
  /** Gets or sets the status. */
  Status?: TaskCompletionStatus;
}
