/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { TaskState } from "./taskState";
import type { TaskInfoLastExecutionResult } from "./taskInfoLastExecutionResult";
import type { TaskTriggerInfo } from "./taskTriggerInfo";

/**
 * Class TaskInfo.
 */
export interface TaskInfo {
  /** Gets or sets the name. */
  Name?: string | null;
  /** Gets or sets the state of the task. */
  State?: TaskState;
  /** Gets or sets the progress. */
  CurrentProgressPercentage?: number | null;
  /** Gets or sets the id. */
  Id?: string | null;
  /** Gets or sets the last execution result. */
  LastExecutionResult?: TaskInfoLastExecutionResult;
  /** Gets or sets the triggers. */
  Triggers?: TaskTriggerInfo[] | null;
  /** Gets or sets the description. */
  Description?: string | null;
  /** Gets or sets the category. */
  Category?: string | null;
  /** Gets or sets a value indicating whether this instance is hidden. */
  IsHidden?: boolean;
  /** Gets or sets the key. */
  Key?: string | null;
}
