/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Enum TaskCompletionStatus.
 */
export type TaskCompletionStatus =
  (typeof TaskCompletionStatus)[keyof typeof TaskCompletionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskCompletionStatus = {
  Completed: "Completed",
  Failed: "Failed",
  Cancelled: "Cancelled",
  Aborted: "Aborted",
} as const;
