/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { TaskTriggerInfoDayOfWeek } from "./taskTriggerInfoDayOfWeek";

/**
 * Class TaskTriggerInfo.
 */
export interface TaskTriggerInfo {
  /**
   * Gets or sets the day of week.
   * @nullable
   */
  DayOfWeek?: TaskTriggerInfoDayOfWeek;
  /**
   * Gets or sets the interval.
   * @nullable
   */
  IntervalTicks?: number | null;
  /**
   * Gets or sets the maximum runtime ticks.
   * @nullable
   */
  MaxRuntimeTicks?: number | null;
  /**
   * Gets or sets the time of day.
   * @nullable
   */
  TimeOfDayTicks?: number | null;
  /**
   * Gets or sets the type.
   * @nullable
   */
  Type?: string | null;
}
