/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { TrailerInfo } from "./trailerInfo";

/**
 * @nullable
 */
export type TrailerInfoRemoteSearchQuerySearchInfo = TrailerInfo | null;
