/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { DlnaProfileType } from "./dlnaProfileType";
import type { TranscodeSeekInfo } from "./transcodeSeekInfo";
import type { EncodingContext } from "./encodingContext";
import type { ProfileCondition } from "./profileCondition";

export interface TranscodingProfile {
  Container?: string;
  Type?: DlnaProfileType;
  VideoCodec?: string;
  AudioCodec?: string;
  Protocol?: string;
  EstimateContentLength?: boolean;
  EnableMpegtsM2TsMode?: boolean;
  TranscodeSeekInfo?: TranscodeSeekInfo;
  CopyTimestamps?: boolean;
  Context?: EncodingContext;
  EnableSubtitlesInManifest?: boolean;
  MaxAudioChannels?: string | null;
  MinSegments?: number;
  SegmentLength?: number;
  BreakOnNonKeyFrames?: boolean;
  Conditions?: ProfileCondition[];
}
