/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { TranscodingInfoHardwareAccelerationType } from './transcodingInfoHardwareAccelerationType';
import type { TranscodeReason } from './transcodeReason';

export interface TranscodingInfo {
  AudioCodec?: string | null;
  VideoCodec?: string | null;
  Container?: string | null;
  IsVideoDirect?: boolean;
  IsAudioDirect?: boolean;
  Bitrate?: number | null;
  Framerate?: number | null;
  CompletionPercentage?: number | null;
  Width?: number | null;
  Height?: number | null;
  AudioChannels?: number | null;
  HardwareAccelerationType?: TranscodingInfoHardwareAccelerationType;
  TranscodeReasons?: TranscodeReason[];
}
