/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface TunerChannelMapping {
  Name?: string | null;
  ProviderChannelName?: string | null;
  ProviderChannelId?: string | null;
  Id?: string | null;
}
