/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { MediaPathInfo } from './mediaPathInfo';

/**
 * Update library options dto.
 */
export interface UpdateMediaPathRequestDto {
  /** Gets or sets the library name. */
  Name: string;
  /** Gets or sets library folder path information. */
  PathInfo: MediaPathInfo;
}
