/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { UpdateLibraryOptionsDtoLibraryOptions } from "./updateLibraryOptionsDtoLibraryOptions";

/**
 * Update library options dto.
 */
export interface UpdateLibraryOptionsDto {
  /** Gets or sets the library item id. */
  Id?: string;
  /** Gets or sets library options. */
  LibraryOptions?: UpdateLibraryOptionsDtoLibraryOptions;
}
