/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * The update user easy password request body.
 */
export interface UpdateUserEasyPassword {
  /** Gets or sets the new sha1-hashed password. */
  NewPassword?: string | null;
  /** Gets or sets the new password. */
  NewPw?: string | null;
  /** Gets or sets a value indicating whether to reset the password. */
  ResetPassword?: boolean;
}
