/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Upload subtitles dto.
 */
export interface UploadSubtitleDto {
  /** Gets or sets the subtitle data. */
  Data: string;
  /** Gets or sets the subtitle format. */
  Format: string;
  /** Gets or sets a value indicating whether the subtitle is forced. */
  IsForced: boolean;
  /** Gets or sets the subtitle language. */
  Language: string;
}
