/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { UserConfiguration } from "./userConfiguration";

/**
 * Gets or sets the configuration.
 * @nullable
 */
export type UserDtoConfiguration = UserConfiguration | null;
