/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class UserItemDataDto.
 */
export interface UserItemDataDto {
  /** Gets or sets a value indicating whether this instance is favorite. */
  IsFavorite?: boolean;
  /**
   * Gets or sets the item identifier.
   * @nullable
   */
  ItemId?: string | null;
  /**
   * Gets or sets the key.
   * @nullable
   */
  Key?: string | null;
  /**
   * Gets or sets the last played date.
   * @nullable
   */
  LastPlayedDate?: string | null;
  /**
   * Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is likes.
   * @nullable
   */
  Likes?: boolean | null;
  /** Gets or sets the playback position ticks. */
  PlaybackPositionTicks?: number;
  /** Gets or sets the play count. */
  PlayCount?: number;
  /** Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is played. */
  Played?: boolean;
  /**
   * Gets or sets the played percentage.
   * @nullable
   */
  PlayedPercentage?: number | null;
  /**
   * Gets or sets the rating.
   * @nullable
   */
  Rating?: number | null;
  /**
   * Gets or sets the unplayed item count.
   * @nullable
   */
  UnplayedItemCount?: number | null;
}
