/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { AccessSchedule } from "./accessSchedule";
import type { UnratedItem } from "./unratedItem";
import type { SyncPlayUserAccessType } from "./syncPlayUserAccessType";

export interface UserPolicy {
  /** @nullable */
  AccessSchedules?: AccessSchedule[] | null;
  /** @nullable */
  AuthenticationProviderId?: string | null;
  /** @nullable */
  BlockedChannels?: string[] | null;
  /** @nullable */
  BlockedMediaFolders?: string[] | null;
  /** @nullable */
  BlockedTags?: string[] | null;
  /** @nullable */
  BlockUnratedItems?: UnratedItem[] | null;
  EnableAllChannels?: boolean;
  EnableAllDevices?: boolean;
  EnableAllFolders?: boolean;
  EnableAudioPlaybackTranscoding?: boolean;
  EnableContentDeletion?: boolean;
  /** @nullable */
  EnableContentDeletionFromFolders?: string[] | null;
  EnableContentDownloading?: boolean;
  /** @nullable */
  EnabledChannels?: string[] | null;
  /** @nullable */
  EnabledDevices?: string[] | null;
  /** @nullable */
  EnabledFolders?: string[] | null;
  EnableLiveTvAccess?: boolean;
  EnableLiveTvManagement?: boolean;
  EnableMediaConversion?: boolean;
  EnableMediaPlayback?: boolean;
  EnablePlaybackRemuxing?: boolean;
  EnablePublicSharing?: boolean;
  EnableRemoteAccess?: boolean;
  EnableRemoteControlOfOtherUsers?: boolean;
  EnableSharedDeviceControl?: boolean;
  /** Gets or sets a value indicating whether [enable synchronize]. */
  EnableSyncTranscoding?: boolean;
  EnableUserPreferenceAccess?: boolean;
  EnableVideoPlaybackTranscoding?: boolean;
  ForceRemoteSourceTranscoding?: boolean;
  InvalidLoginAttemptCount?: number;
  /** Gets or sets a value indicating whether this instance is administrator. */
  IsAdministrator?: boolean;
  /** Gets or sets a value indicating whether this instance is disabled. */
  IsDisabled?: boolean;
  /** Gets or sets a value indicating whether this instance is hidden. */
  IsHidden?: boolean;
  LoginAttemptsBeforeLockout?: number;
  MaxActiveSessions?: number;
  /**
   * Gets or sets the max parental rating.
   * @nullable
   */
  MaxParentalRating?: number | null;
  /** @nullable */
  PasswordResetProviderId?: string | null;
  RemoteClientBitrateLimit?: number;
  /** Enum SyncPlayUserAccessType. */
  SyncPlayAccess?: SyncPlayUserAccessType;
}
