/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Class UtcTimeResponse.
 */
export interface UtcTimeResponse {
  /** Gets the UTC time when request has been received. */
  RequestReceptionTime?: string;
  /** Gets the UTC time when response has been sent. */
  ResponseTransmissionTime?: string;
}
