/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { LibraryOptions } from "./libraryOptions";

/**
 * @nullable
 */
export type VirtualFolderInfoLibraryOptions = LibraryOptions | null;
