/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */
import type { VirtualFolderInfoCollectionType } from './virtualFolderInfoCollectionType';
import type { VirtualFolderInfoLibraryOptions } from './virtualFolderInfoLibraryOptions';

/**
 * Used to hold information about a user's list of configured virtual folders.
 */
export interface VirtualFolderInfo {
  /** Gets or sets the name. */
  Name?: string | null;
  /** Gets or sets the locations. */
  Locations?: string[] | null;
  /** Gets or sets the type of the collection. */
  CollectionType?: VirtualFolderInfoCollectionType;
  LibraryOptions?: VirtualFolderInfoLibraryOptions;
  /** Gets or sets the item identifier. */
  ItemId?: string | null;
  /** Gets or sets the primary image item identifier. */
  PrimaryImageItemId?: string | null;
  RefreshProgress?: number | null;
  RefreshStatus?: string | null;
}
