/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

export interface XbmcMetadataOptions {
  UserId?: string | null;
  ReleaseDateFormat?: string;
  SaveImagePathsInNfo?: boolean;
  EnablePathSubstitution?: boolean;
  EnableExtraThumbsDuplication?: boolean;
}
