/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Jellyfin API
 * OpenAPI spec version: 10.8.8
 */

/**
 * Defines the MediaBrowser.Model.Dlna.XmlAttribute.
 */
export interface XmlAttribute {
  /** Gets or sets the name of the attribute. */
  Name?: string | null;
  /** Gets or sets the value of the attribute. */
  Value?: string | null;
}
