/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { MonitorTypes } from "./monitorTypes";
import type { AddMovieMethod } from "./addMovieMethod";

export interface AddMovieOptions {
  ignoreEpisodesWithFiles?: boolean;
  ignoreEpisodesWithoutFiles?: boolean;
  monitor?: MonitorTypes;
  searchForMovie?: boolean;
  addMethod?: AddMovieMethod;
}
