/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Language } from "./language";
import type { SourceType } from "./sourceType";

export interface AlternativeTitle {
  /** @nullable */
  cleanTitle?: string | null;
  id?: number;
  language?: Language;
  movieMetadataId?: number;
  sourceId?: number;
  sourceType?: SourceType;
  /** @nullable */
  title?: string | null;
  voteCount?: number;
  votes?: number;
}
