/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { MediaCover } from "./mediaCover";
import type { Ratings } from "./ratings";

export interface CollectionMovieResource {
  /** @nullable */
  cleanTitle?: string | null;
  /** @nullable */
  folder?: string | null;
  /** @nullable */
  genres?: string[] | null;
  /** @nullable */
  images?: MediaCover[] | null;
  /** @nullable */
  imdbId?: string | null;
  /** @nullable */
  overview?: string | null;
  ratings?: Ratings;
  runtime?: number;
  /** @nullable */
  sortTitle?: string | null;
  /** @nullable */
  title?: string | null;
  tmdbId?: number;
  year?: number;
}
