/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { MediaCover } from "./mediaCover";
import type { MovieStatusType } from "./movieStatusType";
import type { CollectionMovieResource } from "./collectionMovieResource";

export interface CollectionResource {
  id?: number;
  title?: string | null;
  sortTitle?: string | null;
  tmdbId?: number;
  images?: MediaCover[] | null;
  overview?: string | null;
  monitored?: boolean;
  rootFolderPath?: string | null;
  qualityProfileId?: number;
  searchOnAdd?: boolean;
  minimumAvailability?: MovieStatusType;
  movies?: CollectionMovieResource[] | null;
  missingMovies?: number;
  tags?: number[] | null;
}
