/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { CommandTrigger } from "./commandTrigger";

export interface Command {
  /** @nullable */
  clientUserAgent?: string | null;
  /** @nullable */
  readonly completionMessage?: string | null;
  readonly isExclusive?: boolean;
  readonly isLongRunning?: boolean;
  readonly isTypeExclusive?: boolean;
  /** @nullable */
  lastExecutionTime?: string | null;
  /** @nullable */
  lastStartTime?: string | null;
  /** @nullable */
  readonly name?: string | null;
  readonly requiresDiskAccess?: boolean;
  sendUpdatesToClient?: boolean;
  suppressMessages?: boolean;
  trigger?: CommandTrigger;
  readonly updateScheduledTask?: boolean;
}
