/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { MediaCover } from "./mediaCover";
import type { CreditType } from "./creditType";

export interface CreditResource {
  /** @nullable */
  character?: string | null;
  /** @nullable */
  creditTmdbId?: string | null;
  /** @nullable */
  department?: string | null;
  id?: number;
  /** @nullable */
  images?: MediaCover[] | null;
  /** @nullable */
  job?: string | null;
  movieMetadataId?: number;
  order?: number;
  /** @nullable */
  personName?: string | null;
  personTmdbId?: number;
  type?: CreditType;
}
