/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type CreditType = (typeof CreditType)[keyof typeof CreditType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreditType = {
  cast: "cast",
  crew: "crew",
} as const;
