/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { DownloadProtocol } from "./downloadProtocol";

export interface DelayProfileResource {
  bypassIfHighestQuality?: boolean;
  enableTorrent?: boolean;
  enableUsenet?: boolean;
  id?: number;
  order?: number;
  preferredProtocol?: DownloadProtocol;
  /** @nullable */
  tags?: number[] | null;
  torrentDelay?: number;
  usenetDelay?: number;
}
