/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type DeleteApiV3QueueIdParams = {
  removeFromClient?: boolean;
  blocklist?: boolean;
};
