/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface DiskSpaceResource {
  id?: number;
  path?: string | null;
  label?: string | null;
  freeSpace?: number;
  totalSpace?: number;
}
