/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type ExtraFileType = (typeof ExtraFileType)[keyof typeof ExtraFileType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExtraFileType = {
  subtitle: "subtitle",
  metadata: "metadata",
  other: "other",
} as const;
