/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type HealthCheckResult =
  (typeof HealthCheckResult)[keyof typeof HealthCheckResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckResult = {
  ok: "ok",
  notice: "notice",
  warning: "warning",
  error: "error",
} as const;
