/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Field } from "./field";
import type { ProviderMessage } from "./providerMessage";

export interface ImportExclusionsResource {
  id?: number;
  name?: string | null;
  fields?: Field[] | null;
  implementationName?: string | null;
  implementation?: string | null;
  configContract?: string | null;
  infoLink?: string | null;
  message?: ProviderMessage;
  tags?: number[] | null;
  presets?: ImportExclusionsResource[] | null;
  tmdbId?: number;
  movieTitle?: string | null;
  movieYear?: number;
}
