/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface IndexerConfigResource {
  id?: number;
  minimumAge?: number;
  maximumSize?: number;
  retention?: number;
  rssSyncInterval?: number;
  preferIndexerFlags?: boolean;
  availabilityDelay?: number;
  allowHardcodedSubs?: boolean;
  whitelistedHardcodedSubs?: string | null;
}
