/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface LogFileResource {
  /** @nullable */
  contentsUrl?: string | null;
  /** @nullable */
  downloadUrl?: string | null;
  /** @nullable */
  filename?: string | null;
  id?: number;
  lastWriteTime?: string;
}
