/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { MovieResource } from "./movieResource";
import type { QualityModel } from "./qualityModel";
import type { Language } from "./language";
import type { Rejection } from "./rejection";

export interface ManualImportReprocessResource {
  id?: number;
  path?: string | null;
  movieId?: number;
  movie?: MovieResource;
  quality?: QualityModel;
  languages?: Language[] | null;
  releaseGroup?: string | null;
  downloadId?: string | null;
  rejections?: Rejection[] | null;
}
