/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface MediaInfoResource {
  id?: number;
  audioBitrate?: number;
  audioChannels?: number;
  audioCodec?: string | null;
  audioLanguages?: string | null;
  audioStreamCount?: number;
  videoBitDepth?: number;
  videoBitrate?: number;
  videoCodec?: string | null;
  videoDynamicRangeType?: string | null;
  videoFps?: number;
  resolution?: string | null;
  runTime?: string | null;
  scanType?: string | null;
  subtitles?: string | null;
}
