/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type MovieRuntimeFormatType =
  (typeof MovieRuntimeFormatType)[keyof typeof MovieRuntimeFormatType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MovieRuntimeFormatType = {
  hoursMinutes: "hoursMinutes",
  minutes: "minutes",
} as const;
