/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Language } from "./language";

export interface MovieTranslation {
  /** @nullable */
  cleanTitle?: string | null;
  id?: number;
  language?: Language;
  movieMetadataId?: number;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  title?: string | null;
}
