/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { MovieResource } from "./movieResource";
import type { ParsedMovieInfo } from "./parsedMovieInfo";

export interface ParseResource {
  id?: number;
  movie?: MovieResource;
  parsedMovieInfo?: ParsedMovieInfo;
  /** @nullable */
  title?: string | null;
}
