/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { ProviderMessageType } from "./providerMessageType";

export interface ProviderMessage {
  message?: string | null;
  type?: ProviderMessageType;
}
