/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type ProviderMessageType =
  (typeof ProviderMessageType)[keyof typeof ProviderMessageType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProviderMessageType = {
  info: "info",
  warning: "warning",
  error: "error",
} as const;
