/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Source } from "./source";
import type { Modifier } from "./modifier";

export interface Quality {
  id?: number;
  name?: string | null;
  source?: Source;
  resolution?: number;
  modifier?: Modifier;
}
