/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Quality } from "./quality";

export interface QualityProfileQualityItemResource {
  allowed?: boolean;
  id?: number;
  /** @nullable */
  items?: QualityProfileQualityItemResource[] | null;
  /** @nullable */
  name?: string | null;
  quality?: Quality;
}
