/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { RatingType } from "./ratingType";

export interface RatingChild {
  type?: RatingType;
  value?: number;
  votes?: number;
}
