/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type RatingType = (typeof RatingType)[keyof typeof RatingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RatingType = {
  user: "user",
  critic: "critic",
} as const;
