/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { RatingType } from "./ratingType";

export interface RatingChild {
  votes?: number;
  value?: number;
  type?: RatingType;
}
