/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface RemotePathMappingResource {
  id?: number;
  host?: string | null;
  remotePath?: string | null;
  localPath?: string | null;
}
