/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type RescanAfterRefreshType =
  (typeof RescanAfterRefreshType)[keyof typeof RescanAfterRefreshType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RescanAfterRefreshType = {
  always: "always",
  afterManual: "afterManual",
  never: "never",
} as const;
