/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface RestrictionResource {
  id?: number;
  /** @nullable */
  ignored?: string | null;
  /** @nullable */
  preferred?: string | null;
  /** @nullable */
  required?: string | null;
  /** @nullable */
  tags?: number[] | null;
}
