/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { UnmappedFolder } from "./unmappedFolder";

export interface RootFolderResource {
  accessible?: boolean;
  /** @nullable */
  freeSpace?: number | null;
  id?: number;
  /** @nullable */
  path?: string | null;
  /** @nullable */
  unmappedFolders?: UnmappedFolder[] | null;
}
