/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type TMDbCountryCode =
  (typeof TMDbCountryCode)[keyof typeof TMDbCountryCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TMDbCountryCode = {
  au: "au",
  br: "br",
  ca: "ca",
  fr: "fr",
  de: "de",
  gb: "gb",
  ie: "ie",
  it: "it",
  es: "es",
  us: "us",
  nz: "nz",
} as const;
