/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Radarr
 * Radarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { MovieRuntimeFormatType } from "./movieRuntimeFormatType";

export interface UiConfigResource {
  /** @nullable */
  calendarWeekColumnHeader?: string | null;
  enableColorImpairedMode?: boolean;
  firstDayOfWeek?: number;
  id?: number;
  /** @nullable */
  longDateFormat?: string | null;
  movieInfoLanguage?: number;
  movieRuntimeFormat?: MovieRuntimeFormatType;
  /** @nullable */
  shortDateFormat?: string | null;
  showRelativeDates?: boolean;
  /** @nullable */
  theme?: string | null;
  /** @nullable */
  timeFormat?: string | null;
  uiLanguage?: number;
}
