/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AlbumLazyLoaded } from "./albumLazyLoaded";
import type { Medium } from "./medium";
import type { TrackListLazyLoaded } from "./trackListLazyLoaded";

export interface AlbumRelease {
  album?: AlbumLazyLoaded;
  albumId?: number;
  /** @nullable */
  country?: string[] | null;
  /** @nullable */
  disambiguation?: string | null;
  duration?: number;
  /** @nullable */
  foreignReleaseId?: string | null;
  id?: number;
  /** @nullable */
  label?: string[] | null;
  /** @nullable */
  media?: Medium[] | null;
  monitored?: boolean;
  /** @nullable */
  oldForeignReleaseIds?: string[] | null;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  title?: string | null;
  trackCount?: number;
  tracks?: TrackListLazyLoaded;
}
