/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AddAlbumOptions } from "./addAlbumOptions";
import type { AlbumReleaseListLazyLoaded } from "./albumReleaseListLazyLoaded";
import type { ArtistLazyLoaded } from "./artistLazyLoaded";
import type { ArtistMetadataLazyLoaded } from "./artistMetadataLazyLoaded";
import type { MediaCover } from "./mediaCover";
import type { Links } from "./links";
import type { Ratings } from "./ratings";
import type { SecondaryAlbumType } from "./secondaryAlbumType";

export interface Album {
  added?: string;
  addOptions?: AddAlbumOptions;
  albumReleases?: AlbumReleaseListLazyLoaded;
  /** @nullable */
  albumType?: string | null;
  anyReleaseOk?: boolean;
  artist?: ArtistLazyLoaded;
  artistMetadata?: ArtistMetadataLazyLoaded;
  artistMetadataId?: number;
  /** @nullable */
  cleanTitle?: string | null;
  /** @nullable */
  disambiguation?: string | null;
  /** @nullable */
  foreignAlbumId?: string | null;
  /** @nullable */
  genres?: string[] | null;
  id?: number;
  /** @nullable */
  images?: MediaCover[] | null;
  /** @nullable */
  lastInfoSync?: string | null;
  /** @nullable */
  links?: Links[] | null;
  monitored?: boolean;
  /** @nullable */
  oldForeignAlbumIds?: string[] | null;
  /** @nullable */
  overview?: string | null;
  profileId?: number;
  ratings?: Ratings;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  secondaryTypes?: SecondaryAlbumType[] | null;
  /** @nullable */
  title?: string | null;
}
