/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Medium } from "./medium";
import type { AlbumLazyLoaded } from "./albumLazyLoaded";
import type { TrackListLazyLoaded } from "./trackListLazyLoaded";

export interface AlbumRelease {
  id?: number;
  albumId?: number;
  foreignReleaseId?: string | null;
  oldForeignReleaseIds?: string[] | null;
  title?: string | null;
  status?: string | null;
  duration?: number;
  label?: string[] | null;
  disambiguation?: string | null;
  country?: string[] | null;
  releaseDate?: string | null;
  media?: Medium[] | null;
  trackCount?: number;
  monitored?: boolean;
  album?: AlbumLazyLoaded;
  tracks?: TrackListLazyLoaded;
}
