/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type ArtistStatusType =
  (typeof ArtistStatusType)[keyof typeof ArtistStatusType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArtistStatusType = {
  continuing: "continuing",
  ended: "ended",
} as const;
