/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";
import type { ApplyTags } from "./applyTags";

export interface ArtistEditorResource {
  artistIds?: number[] | null;
  monitored?: boolean | null;
  monitorNewItems?: NewItemMonitorTypes;
  qualityProfileId?: number | null;
  metadataProfileId?: number | null;
  rootFolderPath?: string | null;
  tags?: number[] | null;
  applyTags?: ApplyTags;
  moveFiles?: boolean;
  deleteFiles?: boolean;
}
