/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Artist } from "./artist";

export interface ArtistLazyLoaded {
  readonly isLoaded?: boolean;
  value?: Artist;
}
