/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { MediaCover } from "./mediaCover";
import type { Links } from "./links";
import type { Member } from "./member";
import type { Ratings } from "./ratings";
import type { ArtistStatusType } from "./artistStatusType";

export interface ArtistMetadata {
  /** @nullable */
  aliases?: string[] | null;
  /** @nullable */
  disambiguation?: string | null;
  /** @nullable */
  foreignArtistId?: string | null;
  /** @nullable */
  genres?: string[] | null;
  id?: number;
  /** @nullable */
  images?: MediaCover[] | null;
  /** @nullable */
  links?: Links[] | null;
  /** @nullable */
  members?: Member[] | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  oldForeignArtistIds?: string[] | null;
  /** @nullable */
  overview?: string | null;
  ratings?: Ratings;
  status?: ArtistStatusType;
  /** @nullable */
  type?: string | null;
}
