/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AddArtistOptions } from "./addArtistOptions";
import type { MediaCover } from "./mediaCover";
import type { Album } from "./album";
import type { Links } from "./links";
import type { Member } from "./member";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";
import type { Ratings } from "./ratings";
import type { ArtistStatisticsResource } from "./artistStatisticsResource";
import type { ArtistStatusType } from "./artistStatusType";

export interface ArtistResource {
  added?: string;
  addOptions?: AddArtistOptions;
  /** @nullable */
  allMusicId?: string | null;
  artistMetadataId?: number;
  /** @nullable */
  artistName?: string | null;
  /** @nullable */
  artistType?: string | null;
  /** @nullable */
  cleanName?: string | null;
  /** @nullable */
  disambiguation?: string | null;
  discogsId?: number;
  readonly ended?: boolean;
  /** @nullable */
  folder?: string | null;
  /** @nullable */
  foreignArtistId?: string | null;
  /** @nullable */
  genres?: string[] | null;
  id?: number;
  /** @nullable */
  images?: MediaCover[] | null;
  lastAlbum?: Album;
  /** @nullable */
  links?: Links[] | null;
  /** @nullable */
  mbId?: string | null;
  /** @nullable */
  members?: Member[] | null;
  metadataProfileId?: number;
  monitored?: boolean;
  monitorNewItems?: NewItemMonitorTypes;
  nextAlbum?: Album;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  path?: string | null;
  qualityProfileId?: number;
  ratings?: Ratings;
  /** @nullable */
  remotePoster?: string | null;
  /** @nullable */
  rootFolderPath?: string | null;
  /** @nullable */
  sortName?: string | null;
  statistics?: ArtistStatisticsResource;
  status?: ArtistStatusType;
  tadbId?: number;
  /** @nullable */
  tags?: number[] | null;
}
