/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Artist } from "./artist";

export interface ArtistLazyLoaded {
  value?: Artist;
  readonly isLoaded?: boolean;
}
