/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ArtistResource } from "./artistResource";
import type { CustomFormatResource } from "./customFormatResource";
import type { DownloadProtocol } from "./downloadProtocol";
import type { QualityModel } from "./qualityModel";

export interface BlocklistResource {
  /** @nullable */
  albumIds?: number[] | null;
  artist?: ArtistResource;
  artistId?: number;
  /** @nullable */
  customFormats?: CustomFormatResource[] | null;
  date?: string;
  id?: number;
  /** @nullable */
  indexer?: string | null;
  /** @nullable */
  message?: string | null;
  protocol?: DownloadProtocol;
  quality?: QualityModel;
  /** @nullable */
  sourceTitle?: string | null;
}
