/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ICustomFormatSpecification } from "./iCustomFormatSpecification";

export interface CustomFormat {
  id?: number;
  name?: string | null;
  includeCustomFormatWhenRenaming?: boolean;
  specifications?: ICustomFormatSpecification[] | null;
}
