/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type EntityHistoryEventType =
  (typeof EntityHistoryEventType)[keyof typeof EntityHistoryEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntityHistoryEventType = {
  unknown: "unknown",
  grabbed: "grabbed",
  artistFolderImported: "artistFolderImported",
  trackFileImported: "trackFileImported",
  downloadFailed: "downloadFailed",
  trackFileDeleted: "trackFileDeleted",
  trackFileRenamed: "trackFileRenamed",
  albumImportIncomplete: "albumImportIncomplete",
  downloadImported: "downloadImported",
  trackFileRetagged: "trackFileRetagged",
  downloadIgnored: "downloadIgnored",
} as const;
