/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { EntityHistoryEventType } from "./entityHistoryEventType";

export type GetApiV1HistoryArtistParams = {
  artistId?: number;
  albumId?: number;
  eventType?: EntityHistoryEventType;
  includeArtist?: boolean;
  includeAlbum?: boolean;
  includeTrack?: boolean;
};
