/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1ConfigNamingExamplesParams = {
  RenameTracks?: boolean;
  ReplaceIllegalCharacters?: boolean;
  ColonReplacementFormat?: number;
  StandardTrackFormat?: string;
  MultiDiscTrackFormat?: string;
  ArtistFolderFormat?: string;
  IncludeArtistName?: boolean;
  IncludeAlbumTitle?: boolean;
  IncludeQuality?: boolean;
  ReplaceSpaces?: boolean;
  Separator?: string;
  NumberStyle?: string;
  Id?: number;
  ResourceName?: string;
};
