/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type GetFeedV1CalendarLidarrIcsParams = {
  pastDays?: number;
  futureDays?: number;
  tagList?: string;
  unmonitored?: boolean;
};
