/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type HealthCheckResult =
  (typeof HealthCheckResult)[keyof typeof HealthCheckResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckResult = {
  ok: "ok",
  notice: "notice",
  warning: "warning",
  error: "error",
} as const;
