/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { QualityModel } from "./qualityModel";
import type { CustomFormatResource } from "./customFormatResource";
import type { EntityHistoryEventType } from "./entityHistoryEventType";
import type { HistoryResourceData } from "./historyResourceData";
import type { AlbumResource } from "./albumResource";
import type { ArtistResource } from "./artistResource";
import type { TrackResource } from "./trackResource";

export interface HistoryResource {
  id?: number;
  albumId?: number;
  artistId?: number;
  trackId?: number;
  sourceTitle?: string | null;
  quality?: QualityModel;
  customFormats?: CustomFormatResource[] | null;
  customFormatScore?: number;
  qualityCutoffNotMet?: boolean;
  date?: string;
  downloadId?: string | null;
  eventType?: EntityHistoryEventType;
  data?: HistoryResourceData;
  album?: AlbumResource;
  artist?: ArtistResource;
  track?: TrackResource;
}
