/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface ICustomFormatSpecification {
  readonly order?: number;
  readonly infoLink?: string | null;
  readonly implementationName?: string | null;
  name?: string | null;
  negate?: boolean;
  required?: boolean;
}
