/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type ImportListType =
  (typeof ImportListType)[keyof typeof ImportListType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImportListType = {
  program: "program",
  spotify: "spotify",
  lastFm: "lastFm",
  other: "other",
  advanced: "advanced",
} as const;
