/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Field } from "./field";
import type { ImportListType } from "./importListType";
import type { ProviderMessage } from "./providerMessage";
import type { TimeSpan } from "./timeSpan";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";
import type { ImportListMonitorType } from "./importListMonitorType";

export interface ImportListResource {
  /** @nullable */
  configContract?: string | null;
  enableAutomaticAdd?: boolean;
  /** @nullable */
  fields?: Field[] | null;
  id?: number;
  /** @nullable */
  implementation?: string | null;
  /** @nullable */
  implementationName?: string | null;
  /** @nullable */
  infoLink?: string | null;
  listOrder?: number;
  listType?: ImportListType;
  message?: ProviderMessage;
  metadataProfileId?: number;
  minRefreshInterval?: TimeSpan;
  monitorNewItems?: NewItemMonitorTypes;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  presets?: ImportListResource[] | null;
  qualityProfileId?: number;
  /** @nullable */
  rootFolderPath?: string | null;
  shouldMonitor?: ImportListMonitorType;
  shouldMonitorExisting?: boolean;
  shouldSearch?: boolean;
  /** @nullable */
  tags?: number[] | null;
}
