/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Field } from "./field";
import type { ProviderMessage } from "./providerMessage";
import type { ImportListMonitorType } from "./importListMonitorType";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";
import type { ImportListType } from "./importListType";
import type { TimeSpan } from "./timeSpan";

export interface ImportListResource {
  id?: number;
  name?: string | null;
  fields?: Field[] | null;
  implementationName?: string | null;
  implementation?: string | null;
  configContract?: string | null;
  infoLink?: string | null;
  message?: ProviderMessage;
  tags?: number[] | null;
  presets?: ImportListResource[] | null;
  enableAutomaticAdd?: boolean;
  shouldMonitor?: ImportListMonitorType;
  shouldMonitorExisting?: boolean;
  shouldSearch?: boolean;
  rootFolderPath?: string | null;
  monitorNewItems?: NewItemMonitorTypes;
  qualityProfileId?: number;
  metadataProfileId?: number;
  listType?: ImportListType;
  listOrder?: number;
  minRefreshInterval?: TimeSpan;
}
