/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface LogFileResource {
  /** @nullable */
  contentsUrl?: string | null;
  /** @nullable */
  downloadUrl?: string | null;
  /** @nullable */
  filename?: string | null;
  id?: number;
  lastWriteTime?: string;
}
