/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface MediumResource {
  mediumNumber?: number;
  mediumName?: string | null;
  mediumFormat?: string | null;
}
