/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type MediaCoverTypes =
  (typeof MediaCoverTypes)[keyof typeof MediaCoverTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaCoverTypes = {
  unknown: "unknown",
  poster: "poster",
  banner: "banner",
  fanart: "fanart",
  screenshot: "screenshot",
  headshot: "headshot",
  cover: "cover",
  disc: "disc",
  logo: "logo",
  clearlogo: "clearlogo",
} as const;
