/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { MediaCover } from "./mediaCover";

export interface Member {
  name?: string | null;
  instrument?: string | null;
  images?: MediaCover[] | null;
}
