/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ProfilePrimaryAlbumTypeItemResource } from "./profilePrimaryAlbumTypeItemResource";
import type { ProfileReleaseStatusItemResource } from "./profileReleaseStatusItemResource";
import type { ProfileSecondaryAlbumTypeItemResource } from "./profileSecondaryAlbumTypeItemResource";

export interface MetadataProfileResource {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  primaryAlbumTypes?: ProfilePrimaryAlbumTypeItemResource[] | null;
  /** @nullable */
  releaseStatuses?: ProfileReleaseStatusItemResource[] | null;
  /** @nullable */
  secondaryAlbumTypes?: ProfileSecondaryAlbumTypeItemResource[] | null;
}
