/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ProfilePrimaryAlbumTypeItem } from "./profilePrimaryAlbumTypeItem";
import type { ProfileSecondaryAlbumTypeItem } from "./profileSecondaryAlbumTypeItem";
import type { ProfileReleaseStatusItem } from "./profileReleaseStatusItem";

export interface MetadataProfile {
  id?: number;
  name?: string | null;
  primaryAlbumTypes?: ProfilePrimaryAlbumTypeItem[] | null;
  secondaryAlbumTypes?: ProfileSecondaryAlbumTypeItem[] | null;
  releaseStatuses?: ProfileReleaseStatusItem[] | null;
}
