/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ProfilePrimaryAlbumTypeItemResource } from "./profilePrimaryAlbumTypeItemResource";
import type { ProfileSecondaryAlbumTypeItemResource } from "./profileSecondaryAlbumTypeItemResource";
import type { ProfileReleaseStatusItemResource } from "./profileReleaseStatusItemResource";

export interface MetadataProfileResource {
  id?: number;
  name?: string | null;
  primaryAlbumTypes?: ProfilePrimaryAlbumTypeItemResource[] | null;
  secondaryAlbumTypes?: ProfileSecondaryAlbumTypeItemResource[] | null;
  releaseStatuses?: ProfileReleaseStatusItemResource[] | null;
}
