/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface NamingConfigResource {
  /** @nullable */
  artistFolderFormat?: string | null;
  colonReplacementFormat?: number;
  id?: number;
  includeAlbumTitle?: boolean;
  includeArtistName?: boolean;
  includeQuality?: boolean;
  /** @nullable */
  multiDiscTrackFormat?: string | null;
  /** @nullable */
  numberStyle?: string | null;
  renameTracks?: boolean;
  replaceIllegalCharacters?: boolean;
  replaceSpaces?: boolean;
  /** @nullable */
  separator?: string | null;
  /** @nullable */
  standardTrackFormat?: string | null;
}
