/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ParsedAlbumInfo } from "./parsedAlbumInfo";
import type { ArtistResource } from "./artistResource";
import type { AlbumResource } from "./albumResource";

export interface ParseResource {
  id?: number;
  title?: string | null;
  parsedAlbumInfo?: ParsedAlbumInfo;
  artist?: ArtistResource;
  albums?: AlbumResource[] | null;
}
