/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ArtistTitleInfo } from "./artistTitleInfo";
import type { IsoCountry } from "./isoCountry";
import type { TimeSpan } from "./timeSpan";
import type { MediaInfoModel } from "./mediaInfoModel";
import type { QualityModel } from "./qualityModel";

export interface ParsedTrackInfo {
  /** @nullable */
  albumMBId?: string | null;
  /** @nullable */
  albumTitle?: string | null;
  /** @nullable */
  artistMBId?: string | null;
  /** @nullable */
  artistTitle?: string | null;
  artistTitleInfo?: ArtistTitleInfo;
  /** @nullable */
  catalogNumber?: string | null;
  /** @nullable */
  cleanTitle?: string | null;
  country?: IsoCountry;
  /** @nullable */
  disambiguation?: string | null;
  discCount?: number;
  discNumber?: number;
  duration?: TimeSpan;
  /** @nullable */
  label?: string | null;
  mediaInfo?: MediaInfoModel;
  quality?: QualityModel;
  /** @nullable */
  recordingMBId?: string | null;
  /** @nullable */
  releaseGroup?: string | null;
  /** @nullable */
  releaseHash?: string | null;
  /** @nullable */
  releaseMBId?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  trackMBId?: string | null;
  /** @nullable */
  trackNumbers?: number[] | null;
  year?: number;
}
