/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { CustomFormat } from "./customFormat";

export interface ProfileFormatItem {
  format?: CustomFormat;
  score?: number;
}
