/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type ProxyType = (typeof ProxyType)[keyof typeof ProxyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProxyType = {
  http: "http",
  socks4: "socks4",
  socks5: "socks5",
} as const;
