/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Quality } from "./quality";

export interface QualityProfileQualityItem {
  id?: number;
  name?: string | null;
  quality?: Quality;
  items?: QualityProfileQualityItem[] | null;
  allowed?: boolean;
}
