/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { QualityProfile } from "./qualityProfile";

export interface QualityProfileLazyLoaded {
  value?: QualityProfile;
  readonly isLoaded?: boolean;
}
