/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { SortDirection } from "./sortDirection";
import type { PagingResourceFilter } from "./pagingResourceFilter";
import type { QueueResource } from "./queueResource";

export interface QueueResourcePagingResource {
  page?: number;
  pageSize?: number;
  sortKey?: string | null;
  sortDirection?: SortDirection;
  filters?: PagingResourceFilter[] | null;
  totalRecords?: number;
  records?: QueueResource[] | null;
}
