/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface QueueStatusResource {
  count?: number;
  errors?: boolean;
  id?: number;
  totalCount?: number;
  unknownCount?: number;
  unknownErrors?: boolean;
  unknownWarnings?: boolean;
  warnings?: boolean;
}
