/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface ReleaseProfileResource {
  enabled?: boolean;
  id?: number;
  /** @nullable */
  ignored?: string[] | null;
  indexerId?: number;
  /** @nullable */
  required?: string[] | null;
  /** @nullable */
  tags?: number[] | null;
}
