/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { QualityModel } from "./qualityModel";
import type { CustomFormatResource } from "./customFormatResource";
import type { DownloadProtocol } from "./downloadProtocol";

export interface ReleaseResource {
  id?: number;
  guid?: string | null;
  quality?: QualityModel;
  qualityWeight?: number;
  age?: number;
  ageHours?: number;
  ageMinutes?: number;
  size?: number;
  indexerId?: number;
  indexer?: string | null;
  releaseGroup?: string | null;
  subGroup?: string | null;
  releaseHash?: string | null;
  title?: string | null;
  discography?: boolean;
  sceneSource?: boolean;
  airDate?: string | null;
  artistName?: string | null;
  albumTitle?: string | null;
  approved?: boolean;
  temporarilyRejected?: boolean;
  rejected?: boolean;
  rejections?: string[] | null;
  publishDate?: string;
  commentUrl?: string | null;
  downloadUrl?: string | null;
  infoUrl?: string | null;
  downloadAllowed?: boolean;
  releaseWeight?: number;
  customFormats?: CustomFormatResource[] | null;
  customFormatScore?: number;
  magnetUrl?: string | null;
  infoHash?: string | null;
  seeders?: number | null;
  leechers?: number | null;
  protocol?: DownloadProtocol;
  artistId?: number | null;
  albumId?: number | null;
}
