/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface RemotePathMappingResource {
  /** @nullable */
  host?: string | null;
  id?: number;
  /** @nullable */
  localPath?: string | null;
  /** @nullable */
  remotePath?: string | null;
}
