/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { MonitorTypes } from "./monitorTypes";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";

export interface RootFolderResource {
  id?: number;
  name?: string | null;
  path?: string | null;
  defaultMetadataProfileId?: number;
  defaultQualityProfileId?: number;
  defaultMonitorOption?: MonitorTypes;
  defaultNewItemMonitorOption?: NewItemMonitorTypes;
  defaultTags?: number[] | null;
  accessible?: boolean;
  freeSpace?: number | null;
  totalSpace?: number | null;
}
