/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { MonitorTypes } from "./monitorTypes";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";

export interface RootFolderResource {
  accessible?: boolean;
  defaultMetadataProfileId?: number;
  defaultMonitorOption?: MonitorTypes;
  defaultNewItemMonitorOption?: NewItemMonitorTypes;
  defaultQualityProfileId?: number;
  /** @nullable */
  defaultTags?: number[] | null;
  /** @nullable */
  freeSpace?: number | null;
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  path?: string | null;
  /** @nullable */
  totalSpace?: number | null;
}
