/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Track } from "./track";

export interface TrackListLazyLoaded {
  readonly isLoaded?: boolean;
  /** @nullable */
  readonly value?: readonly Track[] | null;
}
