/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AlbumLazyLoaded } from "./albumLazyLoaded";
import type { ArtistLazyLoaded } from "./artistLazyLoaded";
import type { MediaInfoModel } from "./mediaInfoModel";
import type { QualityModel } from "./qualityModel";
import type { TrackListLazyLoaded } from "./trackListLazyLoaded";

export interface TrackFile {
  album?: AlbumLazyLoaded;
  albumId?: number;
  artist?: ArtistLazyLoaded;
  dateAdded?: string;
  id?: number;
  mediaInfo?: MediaInfoModel;
  modified?: string;
  /** @nullable */
  originalFilePath?: string | null;
  /** @nullable */
  path?: string | null;
  quality?: QualityModel;
  /** @nullable */
  releaseGroup?: string | null;
  /** @nullable */
  sceneName?: string | null;
  size?: number;
  tracks?: TrackListLazyLoaded;
}
