/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { QualityModel } from "./qualityModel";

export interface TrackFileListResource {
  quality?: QualityModel;
  /** @nullable */
  releaseGroup?: string | null;
  /** @nullable */
  sceneName?: string | null;
  /** @nullable */
  trackFileIds?: number[] | null;
}
