/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { QualityModel } from "./qualityModel";
import type { CustomFormatResource } from "./customFormatResource";
import type { MediaInfoResource } from "./mediaInfoResource";
import type { ParsedTrackInfo } from "./parsedTrackInfo";

export interface TrackFileResource {
  id?: number;
  artistId?: number;
  albumId?: number;
  path?: string | null;
  size?: number;
  dateAdded?: string;
  sceneName?: string | null;
  releaseGroup?: string | null;
  quality?: QualityModel;
  qualityWeight?: number;
  customFormats?: CustomFormatResource[] | null;
  customFormatScore?: number;
  mediaInfo?: MediaInfoResource;
  qualityCutoffNotMet?: boolean;
  audioTags?: ParsedTrackInfo;
}
