/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Ratings } from "./ratings";
import type { AlbumReleaseLazyLoaded } from "./albumReleaseLazyLoaded";
import type { ArtistMetadataLazyLoaded } from "./artistMetadataLazyLoaded";
import type { TrackFileLazyLoaded } from "./trackFileLazyLoaded";
import type { ArtistLazyLoaded } from "./artistLazyLoaded";
import type { Album } from "./album";

export interface Track {
  id?: number;
  foreignTrackId?: string | null;
  oldForeignTrackIds?: string[] | null;
  foreignRecordingId?: string | null;
  oldForeignRecordingIds?: string[] | null;
  albumReleaseId?: number;
  artistMetadataId?: number;
  trackNumber?: string | null;
  absoluteTrackNumber?: number;
  title?: string | null;
  duration?: number;
  explicit?: boolean;
  ratings?: Ratings;
  mediumNumber?: number;
  trackFileId?: number;
  readonly hasFile?: boolean;
  albumRelease?: AlbumReleaseLazyLoaded;
  artistMetadata?: ArtistMetadataLazyLoaded;
  trackFile?: TrackFileLazyLoaded;
  artist?: ArtistLazyLoaded;
  albumId?: number;
  album?: Album;
}
