/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface UiConfigResource {
  id?: number;
  firstDayOfWeek?: number;
  calendarWeekColumnHeader?: string | null;
  shortDateFormat?: string | null;
  longDateFormat?: string | null;
  timeFormat?: string | null;
  showRelativeDates?: boolean;
  enableColorImpairedMode?: boolean;
  uiLanguage?: number;
  expandAlbumByDefault?: boolean;
  expandSingleByDefault?: boolean;
  expandEPByDefault?: boolean;
  expandBroadcastByDefault?: boolean;
  expandOtherByDefault?: boolean;
  theme?: string | null;
}
