/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface Version {
  readonly build?: number;
  readonly major?: number;
  readonly majorRevision?: number;
  readonly minor?: number;
  readonly minorRevision?: number;
  readonly revision?: number;
}
