/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type WriteAudioTagsType =
  (typeof WriteAudioTagsType)[keyof typeof WriteAudioTagsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WriteAudioTagsType = {
  no: "no",
  newFiles: "newFiles",
  allFiles: "allFiles",
  sync: "sync",
} as const;
