/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type AuthenticationRequiredType =
  (typeof AuthenticationRequiredType)[keyof typeof AuthenticationRequiredType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthenticationRequiredType = {
  enabled: "enabled",
  disabledForLocalAddresses: "disabledForLocalAddresses",
} as const;
