/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type AuthenticationType =
  (typeof AuthenticationType)[keyof typeof AuthenticationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthenticationType = {
  none: "none",
  basic: "basic",
  forms: "forms",
  external: "external",
} as const;
