/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Field } from "./field";

export interface AutoTaggingSpecificationSchema {
  /** @nullable */
  fields?: Field[] | null;
  id?: number;
  /** @nullable */
  implementation?: string | null;
  /** @nullable */
  implementationName?: string | null;
  /** @nullable */
  name?: string | null;
  negate?: boolean;
  required?: boolean;
}
