/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type BackupType = (typeof BackupType)[keyof typeof BackupType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BackupType = {
  scheduled: "scheduled",
  manual: "manual",
  update: "update",
} as const;
