/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Language } from "./language";
import type { QualityModel } from "./qualityModel";
import type { CustomFormatResource } from "./customFormatResource";
import type { DownloadProtocol } from "./downloadProtocol";
import type { SeriesResource } from "./seriesResource";

export interface BlocklistResource {
  id?: number;
  seriesId?: number;
  episodeIds?: number[] | null;
  sourceTitle?: string | null;
  languages?: Language[] | null;
  quality?: QualityModel;
  customFormats?: CustomFormatResource[] | null;
  date?: string;
  protocol?: DownloadProtocol;
  indexer?: string | null;
  message?: string | null;
  series?: SeriesResource;
}
