/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { CustomFormatSpecificationSchema } from "./customFormatSpecificationSchema";

export interface CustomFormatResource {
  id?: number;
  /** @nullable */
  includeCustomFormatWhenRenaming?: boolean | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  specifications?: CustomFormatSpecificationSchema[] | null;
}
