/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface DiskSpaceResource {
  freeSpace?: number;
  id?: number;
  /** @nullable */
  label?: string | null;
  /** @nullable */
  path?: string | null;
  totalSpace?: number;
}
