/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Language } from "./language";
import type { QualityModel } from "./qualityModel";
import type { CustomFormatResource } from "./customFormatResource";
import type { MediaInfoResource } from "./mediaInfoResource";

export interface EpisodeFileResource {
  id?: number;
  seriesId?: number;
  seasonNumber?: number;
  relativePath?: string | null;
  path?: string | null;
  size?: number;
  dateAdded?: string;
  sceneName?: string | null;
  releaseGroup?: string | null;
  languages?: Language[] | null;
  quality?: QualityModel;
  customFormats?: CustomFormatResource[] | null;
  mediaInfo?: MediaInfoResource;
  qualityCutoffNotMet?: boolean;
}
