/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type EpisodeTitleRequiredType =
  (typeof EpisodeTitleRequiredType)[keyof typeof EpisodeTitleRequiredType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EpisodeTitleRequiredType = {
  always: "always",
  bulkSeasonReleases: "bulkSeasonReleases",
  never: "never",
} as const;
