/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type GetApiV3CalendarParams = {
  start?: string;
  end?: string;
  unmonitored?: boolean;
  includeSeries?: boolean;
  includeEpisodeFile?: boolean;
  includeEpisodeImages?: boolean;
  tags?: string;
};
