/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type GetApiV3ConfigNamingExamplesParams = {
  RenameEpisodes?: boolean;
  ReplaceIllegalCharacters?: boolean;
  ColonReplacementFormat?: number;
  MultiEpisodeStyle?: number;
  StandardEpisodeFormat?: string;
  DailyEpisodeFormat?: string;
  AnimeEpisodeFormat?: string;
  SeriesFolderFormat?: string;
  SeasonFolderFormat?: string;
  SpecialsFolderFormat?: string;
  IncludeSeriesTitle?: boolean;
  IncludeEpisodeTitle?: boolean;
  IncludeQuality?: boolean;
  ReplaceSpaces?: boolean;
  Separator?: string;
  NumberStyle?: string;
  Id?: number;
  ResourceName?: string;
};
