/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface HttpUri {
  /** @nullable */
  readonly fragment?: string | null;
  /** @nullable */
  readonly fullUri?: string | null;
  /** @nullable */
  readonly host?: string | null;
  /** @nullable */
  readonly path?: string | null;
  /** @nullable */
  readonly port?: number | null;
  /** @nullable */
  readonly query?: string | null;
  /** @nullable */
  readonly scheme?: string | null;
}
