/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Field } from "./field";
import type { ProviderMessage } from "./providerMessage";
import type { MonitorTypes } from "./monitorTypes";
import type { SeriesTypes } from "./seriesTypes";
import type { ImportListType } from "./importListType";
import type { TimeSpan } from "./timeSpan";

export interface ImportListResource {
  id?: number;
  name?: string | null;
  fields?: Field[] | null;
  implementationName?: string | null;
  implementation?: string | null;
  configContract?: string | null;
  infoLink?: string | null;
  message?: ProviderMessage;
  tags?: number[] | null;
  presets?: ImportListResource[] | null;
  enableAutomaticAdd?: boolean;
  shouldMonitor?: MonitorTypes;
  rootFolderPath?: string | null;
  qualityProfileId?: number;
  seriesType?: SeriesTypes;
  seasonFolder?: boolean;
  listType?: ImportListType;
  listOrder?: number;
  minRefreshInterval?: TimeSpan;
}
