/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { ApplyTags } from "./applyTags";

export interface ImportListBulkResource {
  applyTags?: ApplyTags;
  /** @nullable */
  enableAutomaticAdd?: boolean | null;
  /** @nullable */
  ids?: number[] | null;
  /** @nullable */
  qualityProfileId?: number | null;
  /** @nullable */
  rootFolderPath?: string | null;
  /** @nullable */
  tags?: number[] | null;
}
