/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Language } from "./language";
import type { LanguageProfileItemResource } from "./languageProfileItemResource";

export interface LanguageProfileResource {
  cutoff?: Language;
  id?: number;
  /** @nullable */
  languages?: LanguageProfileItemResource[] | null;
  /** @nullable */
  name?: string | null;
  upgradeAllowed?: boolean;
}
