/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface LanguageResource {
  id?: number;
  name?: string | null;
  readonly nameLower?: string | null;
}
