/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { Language } from "./language";

export interface LanguageProfileItemResource {
  id?: number;
  language?: Language;
  allowed?: boolean;
}
