/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { CustomFormatResource } from "./customFormatResource";
import type { EpisodeResource } from "./episodeResource";
import type { Language } from "./language";
import type { QualityModel } from "./qualityModel";
import type { Rejection } from "./rejection";
import type { SeriesResource } from "./seriesResource";

export interface ManualImportResource {
  /** @nullable */
  customFormats?: CustomFormatResource[] | null;
  /** @nullable */
  downloadId?: string | null;
  /** @nullable */
  episodeFileId?: number | null;
  /** @nullable */
  episodes?: EpisodeResource[] | null;
  /** @nullable */
  folderName?: string | null;
  id?: number;
  /** @nullable */
  languages?: Language[] | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  path?: string | null;
  quality?: QualityModel;
  qualityWeight?: number;
  /** @nullable */
  rejections?: Rejection[] | null;
  /** @nullable */
  relativePath?: string | null;
  /** @nullable */
  releaseGroup?: string | null;
  /** @nullable */
  seasonNumber?: number | null;
  series?: SeriesResource;
  size?: number;
}
