/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type MediaCoverTypes =
  (typeof MediaCoverTypes)[keyof typeof MediaCoverTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaCoverTypes = {
  unknown: "unknown",
  poster: "poster",
  banner: "banner",
  fanart: "fanart",
  screenshot: "screenshot",
  headshot: "headshot",
  clearlogo: "clearlogo",
} as const;
