/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type PostLoginBody = {
  Password?: string;
  RememberMe?: string;
  Username?: string;
};
