/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { QualitySource } from "./qualitySource";

export interface Quality {
  id?: number;
  /** @nullable */
  name?: string | null;
  resolution?: number;
  source?: QualitySource;
}
