/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { ProfileFormatItemResource } from "./profileFormatItemResource";
import type { QualityProfileQualityItemResource } from "./qualityProfileQualityItemResource";

export interface QualityProfileResource {
  cutoff?: number;
  cutoffFormatScore?: number;
  /** @nullable */
  formatItems?: ProfileFormatItemResource[] | null;
  id?: number;
  /** @nullable */
  items?: QualityProfileQualityItemResource[] | null;
  minFormatScore?: number;
  /** @nullable */
  name?: string | null;
  upgradeAllowed?: boolean;
}
