/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface ReleaseEpisodeResource {
  /** @nullable */
  absoluteEpisodeNumber?: number | null;
  episodeNumber?: number;
  id?: number;
  seasonNumber?: number;
  /** @nullable */
  title?: string | null;
}
