/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { CustomFormatResource } from "./customFormatResource";
import type { Language } from "./language";
import type { ReleaseEpisodeResource } from "./releaseEpisodeResource";
import type { DownloadProtocol } from "./downloadProtocol";
import type { QualityModel } from "./qualityModel";
import type { AlternateTitleResource } from "./alternateTitleResource";

export interface ReleaseResource {
  /** @nullable */
  absoluteEpisodeNumbers?: number[] | null;
  age?: number;
  ageHours?: number;
  ageMinutes?: number;
  /** @nullable */
  airDate?: string | null;
  approved?: boolean;
  /** @nullable */
  commentUrl?: string | null;
  /** @nullable */
  customFormats?: CustomFormatResource[] | null;
  customFormatScore?: number;
  downloadAllowed?: boolean;
  /** @nullable */
  downloadClientId?: number | null;
  /** @nullable */
  downloadUrl?: string | null;
  /** @nullable */
  episodeId?: number | null;
  /** @nullable */
  episodeIds?: number[] | null;
  /** @nullable */
  episodeNumbers?: number[] | null;
  episodeRequested?: boolean;
  fullSeason?: boolean;
  /** @nullable */
  guid?: string | null;
  id?: number;
  /** @nullable */
  indexer?: string | null;
  indexerId?: number;
  /** @nullable */
  infoHash?: string | null;
  /** @nullable */
  infoUrl?: string | null;
  isAbsoluteNumbering?: boolean;
  isDaily?: boolean;
  isPossibleSpecialEpisode?: boolean;
  /** @nullable */
  languages?: Language[] | null;
  languageWeight?: number;
  /** @nullable */
  leechers?: number | null;
  /** @nullable */
  magnetUrl?: string | null;
  /** @nullable */
  mappedAbsoluteEpisodeNumbers?: number[] | null;
  /** @nullable */
  mappedEpisodeInfo?: ReleaseEpisodeResource[] | null;
  /** @nullable */
  mappedEpisodeNumbers?: number[] | null;
  /** @nullable */
  mappedSeasonNumber?: number | null;
  /** @nullable */
  mappedSeriesId?: number | null;
  protocol?: DownloadProtocol;
  publishDate?: string;
  quality?: QualityModel;
  qualityWeight?: number;
  rejected?: boolean;
  /** @nullable */
  rejections?: string[] | null;
  /** @nullable */
  releaseGroup?: string | null;
  /** @nullable */
  releaseHash?: string | null;
  releaseWeight?: number;
  sceneMapping?: AlternateTitleResource;
  sceneSource?: boolean;
  seasonNumber?: number;
  /** @nullable */
  seeders?: number | null;
  /** @nullable */
  seriesId?: number | null;
  /** @nullable */
  seriesTitle?: string | null;
  /** @nullable */
  shouldOverride?: boolean | null;
  size?: number;
  special?: boolean;
  /** @nullable */
  subGroup?: string | null;
  temporarilyRejected?: boolean;
  /** @nullable */
  title?: string | null;
  tvdbId?: number;
  tvRageId?: number;
}
