/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface RenameEpisodeResource {
  id?: number;
  seriesId?: number;
  seasonNumber?: number;
  episodeNumbers?: number[] | null;
  episodeFileId?: number;
  existingPath?: string | null;
  newPath?: string | null;
}
