/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */
import type { ApplyTags } from "./applyTags";
import type { SeriesTypes } from "./seriesTypes";

export interface SeriesEditorResource {
  addImportListExclusion?: boolean;
  applyTags?: ApplyTags;
  deleteFiles?: boolean;
  /** @nullable */
  monitored?: boolean | null;
  moveFiles?: boolean;
  /** @nullable */
  qualityProfileId?: number | null;
  /** @nullable */
  rootFolderPath?: string | null;
  /** @nullable */
  seasonFolder?: boolean | null;
  /** @nullable */
  seriesIds?: number[] | null;
  seriesType?: SeriesTypes;
  /** @nullable */
  tags?: number[] | null;
}
