/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type SeriesStatusType =
  (typeof SeriesStatusType)[keyof typeof SeriesStatusType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeriesStatusType = {
  continuing: "continuing",
  ended: "ended",
  upcoming: "upcoming",
  deleted: "deleted",
} as const;
