/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface SeriesStatisticsResource {
  seasonCount?: number;
  episodeFileCount?: number;
  episodeCount?: number;
  totalEpisodeCount?: number;
  sizeOnDisk?: number;
  releaseGroups?: string[] | null;
  readonly percentOfEpisodes?: number;
}
