/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export interface SeriesStatisticsResource {
  episodeCount?: number;
  episodeFileCount?: number;
  readonly percentOfEpisodes?: number;
  /** @nullable */
  releaseGroups?: string[] | null;
  seasonCount?: number;
  sizeOnDisk?: number;
  totalEpisodeCount?: number;
}
