/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type TrackedDownloadStatus =
  (typeof TrackedDownloadStatus)[keyof typeof TrackedDownloadStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrackedDownloadStatus = {
  ok: "ok",
  warning: "warning",
  error: "error",
} as const;
