/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sonarr
 * Sonarr API docs
 * OpenAPI spec version: 3.0.0
 */

export type UpdateMechanism =
  (typeof UpdateMechanism)[keyof typeof UpdateMechanism];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMechanism = {
  builtIn: "builtIn",
  script: "script",
  external: "external",
  apt: "apt",
  docker: "docker",
} as const;
