/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateNodesSingleNetworkRequest {
  address?: string;
  address6?: string;
  autostart?: boolean;
  "bond-primary"?: string;
  bond_mode?: string;
  bond_xmit_hash_policy?: string;
  bridge_ports?: string;
  bridge_vlan_aware?: boolean;
  cidr?: string;
  cidr6?: string;
  comments?: string;
  comments6?: string;
  gateway?: string;
  gateway6?: string;
  iface: string;
  mtu?: number;
  netmask?: string;
  netmask6?: number;
  ovs_bonds?: string;
  ovs_bridge?: string;
  ovs_options?: string;
  ovs_ports?: string;
  ovs_tag?: number;
  slaves?: string;
  type: string;
  "vlan-id"?: number;
  "vlan-raw-device"?: string;
}
