/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { CreateNodesSingleQemuSingleAgentFsfreezethawResponseResponseData } from "./createNodesSingleQemuSingleAgentFsfreezethawResponseResponseData";

export type CreateNodesSingleQemuSingleAgentFsfreezethawResponseResponse = {
  /** Returns an object with a single `result` property. */
  data?: CreateNodesSingleQemuSingleAgentFsfreezethawResponseResponseData;
  errors?: string[];
};
