/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateAccessUsersRequest {
  comment?: string;
  email?: string;
  enable?: boolean;
  expire?: number;
  firstname?: string;
  groups?: string;
  keys?: string;
  lastname?: string;
  password?: string;
  userid: string;
}
