/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateNodesSingleSpiceshellRequest {
  cmd?: string;
  "cmd-opts"?: string;
  proxy?: string;
  upgrade?: boolean;
}
