/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateNodesSingleLxcSingleMigrateRequest {
  bwlimit?: number;
  force?: boolean;
  online?: boolean;
  restart?: boolean;
  target: string;
  timeout?: number;
}
