/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { CreateAccessTfaResponseResponseData } from "./createAccessTfaResponseResponseData";

export type CreateAccessTfaResponseResponse = {
  errors?: string[];
  data?: CreateAccessTfaResponseResponseData;
};
