/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateNodesSingleLxcSingleMovevolumeRequest {
  bwlimit?: number;
  delete?: boolean;
  digest?: string;
  storage: string;
  volume: string;
}
