/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateNodesSingleCephInitRequest {
  "cluster-network"?: string;
  disable_cephx?: boolean;
  min_size?: number;
  network?: string;
  pg_bits?: number;
  size?: number;
}
