/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateNodesSingleMigrateallRequest {
  maxworkers?: number;
  target: string;
  vms?: string;
  "with-local-disks"?: boolean;
}
