/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateClusterAcmePluginsRequest {
  api?: string;
  data?: string;
  disable?: boolean;
  id: string;
  nodes?: string;
  type: string;
  "validation-delay"?: number;
}
