/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateClusterHaGroupsRequest {
  comment?: string;
  group: string;
  nodes: string;
  nofailback?: boolean;
  restricted?: boolean;
  type?: string;
}
