/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

/**
 * Partial, possible server generated, configuration properties.
 */
export type CreateStorageResponseResponseDataConfig = {
  /** The, possible auto-generated, encryption-key. */
  "encryption-key"?: string;
};
