/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface CreateClusterAcmeAccountRequest {
  contact: string;
  directory?: string;
  name?: string;
  tos_url?: string;
}
