/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetAccessDomainsResponseResponseDataItem = {
  /** A comment. The GUI use this text when you select a domain (Realm) on the login window. */
  comment?: string;
  realm?: string;
  /** Two-factor authentication provider. */
  tfa?: string;
  type?: string;
};
