/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetAccessRolesSingleResponseResponseData = {
  "Datastore.Allocate"?: number;
  "Datastore.AllocateSpace"?: number;
  "Datastore.AllocateTemplate"?: number;
  "Datastore.Audit"?: number;
  "Group.Allocate"?: number;
  "Permissions.Modify"?: number;
  "Pool.Allocate"?: number;
  "Realm.Allocate"?: number;
  "Realm.AllocateUser"?: number;
  "SDN.Allocate"?: number;
  "SDN.Audit"?: number;
  "Sys.Audit"?: number;
  "Sys.Console"?: number;
  "Sys.Modify"?: number;
  "Sys.PowerMgmt"?: number;
  "Sys.Syslog"?: number;
  "User.Modify"?: number;
  "VM.Allocate"?: number;
  "VM.Audit"?: number;
  "VM.Backup"?: number;
  "VM.Clone"?: number;
  "VM.Config.CDROM"?: number;
  "VM.Config.Cloudinit"?: number;
  "VM.Config.CPU"?: number;
  "VM.Config.Disk"?: number;
  "VM.Config.HWType"?: number;
  "VM.Config.Memory"?: number;
  "VM.Config.Network"?: number;
  "VM.Config.Options"?: number;
  "VM.Console"?: number;
  "VM.Migrate"?: number;
  "VM.Monitor"?: number;
  "VM.PowerMgmt"?: number;
  "VM.Snapshot"?: number;
  "VM.Snapshot.Rollback"?: number;
};
