/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetAccessUsersSingleTfaResponseResponseData = {
  /** The type of TFA the users realm has set, if any. */
  realm?: string;
  /** The type of TFA the user has set, if any. */
  user?: string;
};
