/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

/**
 * Map of "path" => (Map of "privilege" => "propagate boolean").
 */
export type GetAccessPermissionsResponseResponseData = { [key: string]: any };
