/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetAccessPermissionsResponseResponseData } from "./getAccessPermissionsResponseResponseData";

export type GetAccessPermissionsResponseResponse = {
  /** Map of "path" => (Map of "privilege" => "propagate boolean"). */
  data?: GetAccessPermissionsResponseResponseData;
  errors?: string[];
};
