/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetClusterResourcesResponseResponseDataItem = {
  /** Allowed storage content types (when type == storage). */
  content?: string;
  /** CPU utilization (when type in node,qemu,lxc). */
  cpu?: number;
  /** Used disk space in bytes (when type in storage), used root image spave for VMs (type in qemu,lxc). */
  disk?: string;
  /** HA service status (for HA managed VMs). */
  hastate?: string;
  id?: string;
  /** Support level (when type == node). */
  level?: string;
  /** Number of available CPUs (when type in node,qemu,lxc). */
  maxcpu?: number;
  /** Storage size in bytes (when type in storage), root image size for VMs (type in qemu,lxc). */
  maxdisk?: number;
  /** Number of available memory in bytes (when type in node,qemu,lxc). */
  maxmem?: number;
  /** Used memory in bytes (when type in node,qemu,lxc). */
  mem?: string;
  /** The cluster node name (when type in node,storage,qemu,lxc). */
  node?: string;
  /** The pool name (when type in pool,qemu,lxc). */
  pool?: string;
  /** Resource type dependent status. */
  status?: string;
  /** The storage identifier (when type == storage). */
  storage?: string;
  /** Resource type. */
  type?: string;
  /** Node uptime in seconds (when type in node,qemu,lxc). */
  uptime?: number;
};
