/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetClusterConfigApiversionResponseResponse = {
  errors?: string[];
  /** Cluster Join API version, currently 1 */
  data?: number;
};
