/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetClusterTasksResponseResponseDataItem = {
  upid?: string;
  node?: string;
  id?: string;
  user?: string;
  type?: string;
  starttime?: number;
  endtime?: number;
  status?: string;
  tokenid?: string;
  saved?: string;
};
