/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetClusterStatusResponseResponseDataItem = {
  id?: string;
  /** [node] IP of the resolved nodename. */
  ip?: string;
  /** [node] Proxmox VE Subscription level, indicates if eligible for enterprise support as well as access to the stable Proxmox VE Enterprise Repository. */
  level?: string;
  /** [node] Indicates if this is the responding node. */
  local?: number;
  name?: string;
  /** [node] ID of the node from the corosync configuration. */
  nodeid?: number;
  /** [cluster] Nodes count, including offline nodes. */
  nodes?: number;
  /** [node] Indicates if the node is online or offline. */
  online?: number;
  /** [cluster] Indicates if there is a majority of nodes online to make decisions */
  quorate?: number;
  /** Indicates the type, either cluster or node. The type defines the object properties e.g. quorate available for type cluster. */
  type?: string;
  /** [cluster] Current version of the corosync configuration file. */
  version?: number;
};
