/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetClusterBackupSingleIncludedvolumesResponseResponseDataChildrenItemChildrenItem } from "./getClusterBackupSingleIncludedvolumesResponseResponseDataChildrenItemChildrenItem";

export type GetClusterBackupSingleIncludedvolumesResponseResponseDataChildrenItem =
  {
    /** The volumes of the guest with the information if they will be included in backups. */
    children?: GetClusterBackupSingleIncludedvolumesResponseResponseDataChildrenItemChildrenItem[];
    /** VMID of the guest. */
    id?: number;
    /** Name of the guest */
    name?: string;
    /** Type of the guest, VM, CT or unknown for removed but not purged guests. */
    type?: string;
  };
