/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetClusterResourcesResponseResponseDataItem } from "./getClusterResourcesResponseResponseDataItem";

export type GetClusterResourcesResponseResponse = {
  data?: GetClusterResourcesResponseResponseDataItem[];
  errors?: string[];
};
