/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetClusterFirewallAliasesResponseResponseDataItem } from "./getClusterFirewallAliasesResponseResponseDataItem";

export type GetClusterFirewallAliasesResponseResponse = {
  data?: GetClusterFirewallAliasesResponseResponseDataItem[];
  errors?: string[];
};
