/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetClusterMetricsServerResponseResponseDataItem = {
  /** Flag to disable the plugin. */
  disable?: number;
  /** The ID of the entry. */
  id?: string;
  /** Server network port */
  port?: number;
  /** Server dns name or IP address */
  server?: string;
  /** Plugin type. */
  type?: string;
};
