/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleDnsResponseResponseData = {
  /** First name server IP address. */
  dns1?: string;
  /** Second name server IP address. */
  dns2?: string;
  /** Third name server IP address. */
  dns3?: string;
  /** Search domain for host-name lookup. */
  search?: string;
};
