/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleDisksLvmthinResponseResponseDataItem = {
  /** The name of the thinpool. */
  lv?: string;
  /** The size of the thinpool in bytes. */
  lv_size?: number;
  /** The size of the metadata lv in bytes. */
  metadata_size?: number;
  /** The used bytes of the metadata lv. */
  metadata_used?: number;
  /** The used bytes of the thinpool. */
  used?: number;
};
