/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleQemuSingleAgentGetfsinfoResponseResponseData } from "./getNodesSingleQemuSingleAgentGetfsinfoResponseResponseData";

export type GetNodesSingleQemuSingleAgentGetfsinfoResponseResponse = {
  errors?: string[];
  /** Returns an object with a single `result` property. */
  data?: GetNodesSingleQemuSingleAgentGetfsinfoResponseResponseData;
};
