/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleQemuSingleAgentGethostnameResponseResponseData } from "./getNodesSingleQemuSingleAgentGethostnameResponseResponseData";

export type GetNodesSingleQemuSingleAgentGethostnameResponseResponse = {
  errors?: string[];
  /** Returns an object with a single `result` property. */
  data?: GetNodesSingleQemuSingleAgentGethostnameResponseResponseData;
};
