/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleStorageResponseResponseDataItem = {
  /** Set when storage is accessible. */
  active?: number;
  /** Available storage space in bytes. */
  avail?: number;
  /** Allowed storage content types. */
  content?: string;
  /** Set when storage is enabled (not disabled). */
  enabled?: number;
  /** Shared flag from storage configuration. */
  shared?: number;
  /** The storage identifier. */
  storage?: string;
  /** Total storage space in bytes. */
  total?: number;
  /** Storage type. */
  type?: string;
  /** Used storage space in bytes. */
  used?: number;
  /** Used fraction (used/total). */
  used_fraction?: number;
};
