/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleQemuSingleAgentResponseResponseDataItem } from "./getNodesSingleQemuSingleAgentResponseResponseDataItem";

export type GetNodesSingleQemuSingleAgentResponseResponse = {
  /** Returns the list of Qemu Agent commands */
  data?: GetNodesSingleQemuSingleAgentResponseResponseDataItem[];
  errors?: string[];
};
