/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleLxcSingleFirewallRulesResponseResponseDataItem } from "./getNodesSingleLxcSingleFirewallRulesResponseResponseDataItem";

export type GetNodesSingleLxcSingleFirewallRulesResponseResponse = {
  data?: GetNodesSingleLxcSingleFirewallRulesResponseResponseDataItem[];
  errors?: string[];
};
