/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleVersionResponseResponseData = {
  /** The current installed Proxmox VE Release */
  release?: string;
  /** The short git commit hash ID from which this version was build */
  repoid?: string;
  /** The current installed pve-manager package version */
  version?: string;
};
