/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleDisksListResponseResponseDataItem = {
  /** The device path */
  devpath?: string;
  gpt?: number;
  health?: string;
  model?: string;
  osdid?: number;
  serial?: string;
  size?: number;
  used?: string;
  vendor?: string;
  wwn?: string;
};
