/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleDisksZfsSingleResponseResponseDataChildrenItem = {
  cksum?: number;
  /** An optional message about the vdev. */
  msg?: string;
  /** The name of the vdev or section. */
  name?: string;
  read?: number;
  /** The state of the vdev. */
  state?: string;
  write?: number;
};
