/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleQemuSingleAgentGetmemoryblockinfoResponseResponseData } from "./getNodesSingleQemuSingleAgentGetmemoryblockinfoResponseResponseData";

export type GetNodesSingleQemuSingleAgentGetmemoryblockinfoResponseResponse = {
  /** Returns an object with a single `result` property. */
  data?: GetNodesSingleQemuSingleAgentGetmemoryblockinfoResponseResponseData;
  errors?: string[];
};
