/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleCephMonResponseResponseDataItem } from "./getNodesSingleCephMonResponseResponseDataItem";

export type GetNodesSingleCephMonResponseResponse = {
  errors?: string[];
  data?: GetNodesSingleCephMonResponseResponseDataItem[];
};
