/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleStorageSinglePrunebackupsResponseResponseDataItem = {
  /** Creation time of the backup (seconds since the UNIX epoch). */
  ctime?: number;
  /** Whether the backup would be kept or removed. For backups that don't use the standard naming scheme, it's 'protected'. */
  mark?: string;
  /** One of 'qemu', 'lxc', 'openvz' or 'unknown'. */
  type?: string;
  /** The VM the backup belongs to. */
  vmid?: number;
  /** Backup volume ID. */
  volid?: string;
};
