/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleHardwarePciResponseResponseDataItem = {
  /** The PCI Class of the device. */
  class?: string;
  /** The Device ID. */
  device?: string;
  device_name?: string;
  /** The PCI ID. */
  id?: string;
  /** The IOMMU group in which the device is in. If no IOMMU group is detected, it is set to -1. */
  iommugroup?: number;
  /** If set, marks that the device is capable of creating mediated devices. */
  mdev?: number;
  /** The Subsystem Device ID. */
  subsystem_device?: string;
  subsystem_device_name?: string;
  /** The Subsystem Vendor ID. */
  subsystem_vendor?: string;
  subsystem_vendor_name?: string;
  /** The Vendor ID. */
  vendor?: string;
  vendor_name?: string;
};
