/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodeTasksResponseResponseDataItem = {
  endtime?: number;
  id?: string;
  node?: string;
  pid?: number;
  pstart?: number;
  starttime?: number;
  status?: string;
  type?: string;
  upid?: string;
  user?: string;
};
