/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleCephConfigdbResponseResponseDataItem = {
  can_update_at_runtime?: number;
  level?: string;
  mask?: string;
  name?: string;
  section?: string;
  value?: string;
};
