/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleLxcSingleConfigResponseResponseData = {
  /** OS architecture type. */
  arch?: string;
  /** Console mode. By default, the console command tries to open a connection to one of the available tty devices. By setting cmode to 'console' it tries to attach to /dev/console instead. If you set cmode to 'shell', it simply invokes a shell inside the container (no login). */
  cmode?: string;
  /** Attach a console device (/dev/console) to the container. */
  console?: number;
  /** The number of cores assigned to the container. A container can use all available cores by default. */
  cores?: number;
  /** Limit of CPU usage.

NOTE: If the computer has 2 CPUs, it has a total of '2' CPU time. Value '0' indicates no CPU limit. */
  cpulimit?: number;
  /** CPU weight for a VM. Argument is used in the kernel fair scheduler. The larger the number is, the more CPU time this VM gets. Number is relative to the weights of all the other running VMs.

NOTE: You can disable fair-scheduler configuration by setting this to 0. */
  cpuunits?: number;
  /** Try to be more verbose. For now this only enables debug log-level on start. */
  debug?: number;
  /** Container description. Only used on the configuration web interface. */
  description?: string;
  /** SHA1 digest of configuration file. This can be used to prevent concurrent modifications. */
  digest?: string;
  /** Allow containers access to advanced features. */
  features?: string;
  /** Script that will be exectued during various steps in the containers lifetime. */
  hookscript?: string;
  /** Set a host name for the container. */
  hostname?: string;
  /** Lock/unlock the VM. */
  lock?: string;
  /** Array of lxc low-level configurations ([[key1, value1], [key2, value2] ...]). */
  lxc?: string[][];
  /** Amount of RAM for the VM in MB. */
  memory?: number;
  /** Use volume as container mount point. */
  mp0?: string;
  /** Use volume as container mount point. */
  mp1?: string;
  /** Use volume as container mount point. */
  mp10?: string;
  /** Use volume as container mount point. */
  mp11?: string;
  /** Use volume as container mount point. */
  mp12?: string;
  /** Use volume as container mount point. */
  mp13?: string;
  /** Use volume as container mount point. */
  mp14?: string;
  /** Use volume as container mount point. */
  mp15?: string;
  /** Use volume as container mount point. */
  mp16?: string;
  /** Use volume as container mount point. */
  mp17?: string;
  /** Use volume as container mount point. */
  mp18?: string;
  /** Use volume as container mount point. */
  mp19?: string;
  /** Use volume as container mount point. */
  mp2?: string;
  /** Use volume as container mount point. */
  mp20?: string;
  /** Use volume as container mount point. */
  mp21?: string;
  /** Use volume as container mount point. */
  mp22?: string;
  /** Use volume as container mount point. */
  mp23?: string;
  /** Use volume as container mount point. */
  mp24?: string;
  /** Use volume as container mount point. */
  mp25?: string;
  /** Use volume as container mount point. */
  mp26?: string;
  /** Use volume as container mount point. */
  mp27?: string;
  /** Use volume as container mount point. */
  mp28?: string;
  /** Use volume as container mount point. */
  mp29?: string;
  /** Use volume as container mount point. */
  mp3?: string;
  /** Use volume as container mount point. */
  mp4?: string;
  /** Use volume as container mount point. */
  mp5?: string;
  /** Use volume as container mount point. */
  mp6?: string;
  /** Use volume as container mount point. */
  mp7?: string;
  /** Use volume as container mount point. */
  mp8?: string;
  /** Use volume as container mount point. */
  mp9?: string;
  /** Sets DNS server IP address for a container. Create will automatically use the setting from the host if you neither set searchdomain nor nameserver. */
  nameserver?: string;
  /** Specifies network interfaces for the container. */
  net0?: string;
  /** Specifies network interfaces for the container. */
  net1?: string;
  /** Specifies network interfaces for the container. */
  net10?: string;
  /** Specifies network interfaces for the container. */
  net11?: string;
  /** Specifies network interfaces for the container. */
  net12?: string;
  /** Specifies network interfaces for the container. */
  net13?: string;
  /** Specifies network interfaces for the container. */
  net14?: string;
  /** Specifies network interfaces for the container. */
  net15?: string;
  /** Specifies network interfaces for the container. */
  net16?: string;
  /** Specifies network interfaces for the container. */
  net17?: string;
  /** Specifies network interfaces for the container. */
  net18?: string;
  /** Specifies network interfaces for the container. */
  net19?: string;
  /** Specifies network interfaces for the container. */
  net2?: string;
  /** Specifies network interfaces for the container. */
  net20?: string;
  /** Specifies network interfaces for the container. */
  net21?: string;
  /** Specifies network interfaces for the container. */
  net22?: string;
  /** Specifies network interfaces for the container. */
  net23?: string;
  /** Specifies network interfaces for the container. */
  net24?: string;
  /** Specifies network interfaces for the container. */
  net25?: string;
  /** Specifies network interfaces for the container. */
  net26?: string;
  /** Specifies network interfaces for the container. */
  net27?: string;
  /** Specifies network interfaces for the container. */
  net28?: string;
  /** Specifies network interfaces for the container. */
  net29?: string;
  /** Specifies network interfaces for the container. */
  net3?: string;
  /** Specifies network interfaces for the container. */
  net4?: string;
  /** Specifies network interfaces for the container. */
  net5?: string;
  /** Specifies network interfaces for the container. */
  net6?: string;
  /** Specifies network interfaces for the container. */
  net7?: string;
  /** Specifies network interfaces for the container. */
  net8?: string;
  /** Specifies network interfaces for the container. */
  net9?: string;
  /** Specifies whether a VM will be started during system bootup. */
  onboot?: number;
  /** OS type. This is used to setup configuration inside the container, and corresponds to lxc setup scripts in /usr/share/lxc/config/<ostype>.common.conf. Value 'unmanaged' can be used to skip and OS specific setup. */
  ostype?: string;
  /** Sets the protection flag of the container. This will prevent the CT or CT's disk remove/update operation. */
  protection?: number;
  /** Use volume as container root. */
  rootfs?: string;
  /** Sets DNS search domains for a container. Create will automatically use the setting from the host if you neither set searchdomain nor nameserver. */
  searchdomain?: string;
  /** Startup and shutdown behavior. Order is a non-negative number defining the general startup order. Shutdown in done with reverse ordering. Additionally you can set the 'up' or 'down' delay in seconds, which specifies a delay to wait before the next VM is started or stopped. */
  startup?: string;
  /** Amount of SWAP for the VM in MB. */
  swap?: number;
  /** Tags of the Container. This is only meta information. */
  tags?: string;
  /** Enable/disable Template. */
  template?: number;
  /** Time zone to use in the container. If option isn't set, then nothing will be done. Can be set to 'host' to match the host time zone, or an arbitrary time zone option from /usr/share/zoneinfo/zone.tab */
  timezone?: string;
  /** Specify the number of tty available to the container */
  tty?: number;
  /** Makes the container run as unprivileged user. (Should not be modified manually.) */
  unprivileged?: number;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused0?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused1?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused10?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused11?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused12?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused13?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused14?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused15?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused16?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused17?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused18?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused19?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused2?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused20?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused21?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused22?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused23?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused24?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused25?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused26?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused27?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused28?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused29?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused3?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused4?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused5?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused6?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused7?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused8?: string;
  /** Reference to unused volumes. This is used internally, and should not be modified manually. */
  unused9?: string;
};
