/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleLxcSingleFirewallIpsetSingleSingleResponseResponseData } from "./getNodesSingleLxcSingleFirewallIpsetSingleSingleResponseResponseData";

export type GetNodesSingleLxcSingleFirewallIpsetSingleSingleResponseResponse = {
  errors?: string[];
  data?: GetNodesSingleLxcSingleFirewallIpsetSingleSingleResponseResponseData;
};
