/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleLxcSingleConfigResponseResponseData } from "./getNodesSingleLxcSingleConfigResponseResponseData";

export type GetNodesSingleLxcSingleConfigResponseResponse = {
  data?: GetNodesSingleLxcSingleConfigResponseResponseData;
  errors?: string[];
};
