/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleStorageSingleContentSingleResponseResponseData = {
  /** Format identifier ('raw', 'qcow2', 'subvol', 'iso', 'tgz' ...) */
  format?: string;
  /** Optional notes. */
  notes?: string;
  /** The Path */
  path?: string;
  /** Volume size in bytes. */
  size?: number;
  /** Used space. Please note that most storage plugins do not report anything useful here. */
  used?: number;
};
