/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

/**
 * Last backup verification result, only useful for PBS storages.
 */
export type GetNodesSingleStorageSingleContentResponseResponseDataItemVerification =
  {
    /** Last backup verification state. */
    state?: string;
    /** Last backup verification UPID. */
    upid?: string;
  };
