/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodesSingleCephFsResponseResponseDataItem = {
  /** The name of the data pool. */
  data_pool?: string;
  /** The name of the metadata pool. */
  metadata_pool?: string;
  /** The ceph filesystem name. */
  name?: string;
};
