/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleDisksZfsSingleResponseResponseDataChildrenItem } from "./getNodesSingleDisksZfsSingleResponseResponseDataChildrenItem";

export type GetNodesSingleDisksZfsSingleResponseResponseData = {
  /** Information about the recommended action to fix the state. */
  action?: string;
  /** The pool configuration information, including the vdevs for each section (e.g. spares, cache), may be nested. */
  children?: GetNodesSingleDisksZfsSingleResponseResponseDataChildrenItem[];
  /** Information about the errors on the zpool. */
  errors?: string;
  /** The name of the zpool. */
  name?: string;
  /** Information about the last/current scrub. */
  scan?: string;
  /** The state of the zpool. */
  state?: string;
  /** Information about the state of the zpool. */
  status?: string;
};
