/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { GetNodesSingleHardwarePciSingleMdevResponseResponseDataItem } from "./getNodesSingleHardwarePciSingleMdevResponseResponseDataItem";

export type GetNodesSingleHardwarePciSingleMdevResponseResponse = {
  data?: GetNodesSingleHardwarePciSingleMdevResponseResponseDataItem[];
  errors?: string[];
};
