/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetNodeFirewallOptionsResponseResponseData = {
  /** Enable host firewall rules. */
  enable?: number;
  /** Log level for incoming traffic. */
  log_level_in?: string;
  /** Log level for outgoing traffic. */
  log_level_out?: string;
  /** Enable logging of conntrack information. */
  log_nf_conntrack?: number;
  /** Enable NDP (Neighbor Discovery Protocol). */
  ndp?: number;
  /** Allow invalid packets on connection tracking. */
  nf_conntrack_allow_invalid?: number;
  /** Maximum number of tracked connections. */
  nf_conntrack_max?: number;
  /** Conntrack established timeout. */
  nf_conntrack_tcp_timeout_established?: number;
  /** Conntrack syn recv timeout. */
  nf_conntrack_tcp_timeout_syn_recv?: number;
  /** Enable SMURFS filter. */
  nosmurfs?: number;
  /** Enable synflood protection */
  protection_synflood?: number;
  /** Synflood protection rate burst by ip src. */
  protection_synflood_burst?: number;
  /** Synflood protection rate syn/sec by ip src. */
  protection_synflood_rate?: number;
  /** Log level for SMURFS filter. */
  smurf_log_level?: string;
  /** Log level for illegal tcp flags filter. */
  tcp_flags_log_level?: string;
  /** Filter illegal combinations of TCP flags. */
  tcpflags?: number;
};
