/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export type GetVMSnapshotsResponseResponseDataItem = {
  /** Snapshot description. */
  description?: string;
  /** Snapshot identifier. Value 'current' identifies the current VM. */
  name?: string;
  /** Parent snapshot identifier. */
  parent?: string;
  /** Snapshot creation time */
  snaptime?: number;
  /** Snapshot includes RAM. */
  vmstate?: number;
};
