/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */
import type { MigrateVMResponseResponseDataAllowedNodesItem } from "./migrateVMResponseResponseDataAllowedNodesItem";
import type { MigrateVMResponseResponseDataLocalDisksItem } from "./migrateVMResponseResponseDataLocalDisksItem";
import type { MigrateVMResponseResponseDataLocalResourcesItem } from "./migrateVMResponseResponseDataLocalResourcesItem";
import type { MigrateVMResponseResponseDataNotAllowedNodes } from "./migrateVMResponseResponseDataNotAllowedNodes";

export type MigrateVMResponseResponseData = {
  /** List nodes allowed for offline migration, only passed if VM is offline */
  allowed_nodes?: MigrateVMResponseResponseDataAllowedNodesItem[];
  /** List local disks including CD-Rom, unsused and not referenced disks */
  local_disks?: MigrateVMResponseResponseDataLocalDisksItem[];
  /** List local resources e.g. pci, usb */
  local_resources?: MigrateVMResponseResponseDataLocalResourcesItem[];
  /** List not allowed nodes with additional informations, only passed if VM is offline */
  not_allowed_nodes?: MigrateVMResponseResponseDataNotAllowedNodes;
  running?: number;
};
