/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface UpdateClusterAcmePluginsSingleRequest {
  api?: string;
  data?: string;
  delete?: string;
  digest?: string;
  disable?: boolean;
  nodes?: string;
  "validation-delay"?: number;
}
