/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface UpdateClusterReplicationSingleRequest {
  comment?: string;
  delete?: string;
  digest?: string;
  disable?: boolean;
  rate?: number;
  remove_job?: string;
  schedule?: string;
  source?: string;
}
