/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface UpdateClusterBackupSingleRequest {
  all?: boolean;
  bwlimit?: number;
  compress?: string;
  delete?: string;
  dow?: string;
  dumpdir?: string;
  enabled?: boolean;
  exclude?: string;
  "exclude-path"?: string;
  ionice?: number;
  lockwait?: number;
  mailnotification?: string;
  mailto?: string;
  maxfiles?: number;
  mode?: string;
  node?: string;
  pigz?: number;
  pool?: string;
  "prune-backups"?: string;
  quiet?: boolean;
  remove?: boolean;
  script?: string;
  size?: number;
  starttime: string;
  stdexcludes?: boolean;
  stop?: boolean;
  stopwait?: number;
  storage?: string;
  tmpdir?: string;
  vmid?: string;
  zstd?: number;
}
