/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface UpdateStorageSingleRequest {
  blocksize?: string;
  bwlimit?: string;
  comstar_hg?: string;
  comstar_tg?: string;
  content?: string;
  delete?: string;
  digest?: string;
  disable?: boolean;
  domain?: string;
  "encryption-key"?: string;
  fingerprint?: string;
  format?: string;
  fuse?: boolean;
  is_mountpoint?: string;
  krbd?: boolean;
  lio_tpg?: string;
  maxfiles?: number;
  mkdir?: boolean;
  monhost?: string;
  mountpoint?: string;
  nodes?: string;
  nowritecache?: boolean;
  options?: string;
  password?: string;
  pool?: string;
  port?: number;
  "prune-backups"?: string;
  redundancy?: number;
  saferemove?: boolean;
  saferemove_throughput?: string;
  server?: string;
  server2?: string;
  shared?: boolean;
  smbversion?: string;
  sparse?: boolean;
  subdir?: string;
  tagged_only?: boolean;
  transport?: string;
  username?: string;
}
