/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface UpdateNodesSingleCephPoolsSingleRequest {
  application?: string;
  crush_rule?: string;
  min_size?: number;
  pg_autoscale_mode?: string;
  pg_num?: number;
  size?: number;
}
