/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ProxMox VE API
 * ProxMox VE API
 * OpenAPI spec version: 2.0
 */

export interface UpdateNodesSingleDnsRequest {
  dns1?: string;
  dns2?: string;
  dns3?: string;
  search: string;
}
