import { BaseItemKind } from "./api";

export const filters = [
  {
    id: "Type",
    options: ["Movie", "Series", "Episode", "Person"] as BaseItemKind[],
  },
  {
    id: "Genre",
    options: [
      "Action",
      "Adventure",
      "Animation",
      "Anime",
      "Audiobook",
      "Comedy",
      "Crime",
      "Documentary",
      "Drama",
      "Family",
      "Fantasy",
      "Game Show",
      "History",
      "Horror",
      "Music",
      "Mystery",
      "Psychological",
      "Reality",
      "Romance",
      "School",
      "Science Fiction",
      "Sci-Fi",
      "Slice of Life",
      "Sport",
      "Super Power",
      "Supernatural",
      "Suspense",
      "Talk Show",
      "Thriller",
      "Vampire",
      "violence",
      "War",
      "Western",
    ],
  },
  {
    id: "Status",
    options: ["Played", "Unplayed", "Liked", "Favourite"],
  },
  {
    id: "Order",
    options: ["Ascending", "Descending"],
  },
];
